### ISSUE TITLE
feat: cortex pull supports full HF URL download

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1004]
**Problem**
HF repositories do not all have the same structure, e.g., random file names, varying folder structures. I would like to download a model using an absolute model URL.

**Success Criteria**
When running `cortex pull https://huggingface.co/BafS/gemma-2-2b-it-Q4_K_M-GGUF/blob/main/gemma-2-2b-it-q4_k_m.gguf`, it should pull and run.

**Additional context**

**Comment by dan-menlo** [comment]
We can close this, in favor of @namchuai's full implementation of `cortex pull` here: 

https://github.com/janhq/cortex.cpp/issues/1077

**Comment by dan-menlo** [comment]
Tracking as task in https://github.com/janhq/cortex.cpp/issues/1004
