### ISSUE TITLE
feat: Cortex supports custom API Keys

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1005]
**Problem**
I want to host an in-house AI agent and make it publicly accessible from anywhere, as I have some on-device applications that need to access LM endpoints to function properly.

The concern is that when exposing my self-hosted endpoint without a gate, even a simple one.

**Success Criteria**
`cortex -h 0.0.0.0 -p 1102 -k [my_secret_goes_here]`

**Additional context**

**Comment by dan-menlo** [comment]
Merging this into https://github.com/janhq/cortex.cpp/issues/551
