### ISSUE TITLE
feat: how to monitor cortex inbound requests?

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1007]
**Problem**
I'm testing my copilot alternative setup, but I could not debug the outbound requests there. It would be great if I can debug inbound requests from cortex cli. For now, it just outputs the request path, no request body is logged.

**Success Criteria**
E.g. 
```bash
1723389668 - Request /chat/completions
 { 
   "messages": [ 
      "role": "user", 
      "content": "hello" 
   ], 
   "stream": true, 
   "model": "llama3.1" 
}
```

**Additional context**

**Comment by dan-menlo** [comment]
Merged into #1153
