### ISSUE TITLE
bug: Download models/engine failed cause api server stop

### ISSUE THREAD

**Issue by hiento09** [janhq/cortex.cpp#1010]
**Describe the bug**
When I download a model or engine with a timeout error, api server then will be stopped

**To Reproduce**
1. Install cortex `npm install -g cortexso`
2. Start cortex `cortex`
3. Download engine `cortex engines tensorrt-llm init`
4. Just turn off your internet connection and run cortex again, you will see the error `cortex`

**Expected behavior**
Model or engine should be retried download and api server should not be stopped

**Screenshots**
![image](https://github.com/user-attachments/assets/fa282809-430a-4cad-8927-997689450bf1)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 22.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dan-menlo** [comment]
@vansangpfiev I am reassigning this to the Cortex team - if this issue does not exist for the C++ implementation, you can proceed to close this ticket

**Comment by dan-menlo** [comment]
Let's close this ticket as it's Cortex JS related.

**Comment by dan-menlo** [comment]
Referencing this in main issue #1077 and #1072
