### ISSUE TITLE
feat: TensorRT-LLM better error logs for Cuda/Nvidia driver out of date

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex.cpp#1019]
**Problem**
1. Have an outdated cuda toolkit and nvidia driver
2. Get error message: 
```
× CUDA version 12.3 is not compatible with TensorRT-LLM models. Required version: 12.4
```
3.Install latest cuda toolkit
4. Get the same message
5. Realize also need to install Nvidia Driver (is that where we're checking cuda version?)
6. Issue resolved.

**Success Criteria**
Low hanging fruit is to just give a better error message: 

Your Nvidia Driver and Cuda Toolkit is not compatible with the latest TRT-LLM Models.
Please download the latest: 
[NVIDIA driver](https://www.nvidia.com/Download/index.aspx) version ___ or higher.
[CUDA Toolkit](https://developer.nvidia.com/cuda-toolkit) version ___ or higher.

**Additional context**

**Comment by gabrielle-ong** [comment]
Deprecated due to TensorRT-LLM not supporting Desktop
Parent issue: https://github.com/janhq/cortex.cpp/issues/1742
