### ISSUE TITLE
improve: redirect log to right position

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1054]
Currently: 
- all log from cli and cortex.cpp go to log file
- log from engine go to terminal

Target:
- Log from CLI go to terminal
- Log from cortex.cpp server and engines go to log file

**Comment by nguyenhoangthuan99** [comment]
- [x] cortex llamacpp
- [x] cortex tensorrt llm
- [ ] cortex onnx

**Comment by nguyenhoangthuan99** [comment]
Change the logic for log of cortex.xxxx (engines):
- When inital: loglevel will be `error` and log to file 
- Load model: will include `log_level` and `log_option` in body request to decide

Update:
Both tensorrt llm and llamacpp log logic are changed

**Comment by dan-menlo** [comment]
> * [x]  cortex llamacpp[x]  cortex tensorrt llm[ ]  cortex onnx

@nguyenhoangthuan99 Did we finish the log for ONNX?

**Comment by nguyenhoangthuan99** [comment]
for now we have  [new logger logic](https://github.com/janhq/cortex.cpp/issues/1153#issuecomment-2336928898). We need to update the logger for both 3 engines

- [ ] cortex.llamacpp
- [ ] cortex.tensorrt-llm
- [ ] cortex.onnx
