### ISSUE TITLE
bug: [model_id saved in <model_id>.yaml should be the same with input from terminal]

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1055]
when download model `tinyllama:gguf` the model id should be `tinyllama:gguf` instead of `tinyllama-gguf`

![Image](https://github.com/user-attachments/assets/2a1d9c0d-1c49-460b-bdce-798d9b604333)

**Comment by nguyenhoangthuan99** [comment]
With the model bugs when parse input from terminal 


![Image](https://github.com/user-attachments/assets/0497a3a7-c44e-4311-b974-eb23c2d0427b)

after the CmdInfo the information for `:` is lose so we cannot get exact model_id. For example:
`cortex-cpp pull tinyllama:gguf` we will save the model id `tinyllama-gguf`

**Comment by nguyenhoangthuan99** [comment]
I'll update this issue to discontinue, because this issue no longer appear with new model-id logic in #1154, the model-id `tinyllama:gguf` will be saved in `model.list` file.

**Comment by gabrielle-ong** [comment]
QA: 
Windows, Mac, Ubuntu
confirmed now appears in `cortex models list` `as model_id:variant`
Now saved in sqlite DB rather than models.list
