### ISSUE TITLE
bug: Multiprocess cannot write log to the same file

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1056]
**Problem**
In windows, once a file is taken by one process, other process can not modify it. For example, when the server is writing to log file, it hold `cortex.log`, and if we run CLI command, it cannot write message to `cortex.log`.

**Solution**
In window, we are planning to use Unix Domain Socket to start a thread and write log to file. Below are detail implementation:
- When start server, will create a thread to run UDS to listen messages and write to logfile.
- From server side, override log method of Trantor to send log message to UDS server
- From CLI side, when execute command, check if UDS server is live, if not write directly log to log file.
- With command has `--verbose` flag, log everything to terminal.

**Comment by nguyenhoangthuan99** [comment]
For windows, we are planning to use Unix Domain Socket to communicate between process, only one process will write to log file

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 Question from my side - did we consider having a separate log for CLI and Server?

**Comment by nguyenhoangthuan99** [comment]
we will separate log for CLI and server, details in [this comment ](https://github.com/janhq/cortex.cpp/issues/1153#issuecomment-2336928898)
