### ISSUE TITLE
feat: Cortex model importing

### ISSUE THREAD

**Issue by cloudherder** [janhq/cortex.cpp#1058]
## Goal 

- Cortex can import a model that is already on the user's computer
- Question: by symlink or cp? 
- CLI: `cortex model import <path>`, but how do we specify engine etc? (or scope to only GGUF?)

# Original Post

**Problem**
Even though I already have a GGUF model, I still need to re-pull the model, which seems not very friendly. Could Cortex add a feature to import models?

 It would be even better if the `models` command could directly load a model file, although loading a model not listed in the model ID list might cause an error, but this way users can try using more models.

**Comment by dan-menlo** [comment]
@cloudherder This is an important feature. We will be expanding this to solve for generic model importing in cortex.cpp.

**Comment by cloudherder** [comment]
> @cloudherder This is an important feature. We will be expanding this to solve for generic model importing in cortex.cpp.

I am honored to receive your affirmative response. I will continue to monitor the development of cortex.cpp.

**Comment by 0xSage** [comment]
Given model.list, whats the expected file structure?
Why do we nest imported model yamls in a separate folder called `Imported`
@namchuai 

Currently: 
```sh
/models
    /imported
        model.yaml 
    model.list
```

Shouldn't it be instead:
```sh
    model.yaml
    model.list
```

**Comment by dan-menlo** [comment]
@namchuai @nguyenhoangthuan99 Are we doing this in Sprint 21? (I will move it to Sprint 22 otherwise)

**Comment by nguyenhoangthuan99** [comment]
The `import` command is supported with this PR #1248

**Comment by dan-menlo** [comment]
Closing
