### ISSUE TITLE
epic: `cortex models update <MODEL_ID>`

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1060]
Update model config

**Comment by ux-han** [comment]
@vansangpfiev Can you elaborate more on this thanks

**Comment by dan-menlo** [comment]
This is quite a good idea, but needs to be scoped out further: 

- We would update `model.yaml` from Model library (e.g. if updated)
- For Huggingface, we would update the GGUF file

Scheduling for Sprint 22, as I think we should focus on basic functionality first.

**Comment by dan-menlo** [comment]
I am closing this ticket as I don't think models will be updated - just download a new version
