### ISSUE TITLE
feat: Configurable Log path for main program and dependencies

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1062]
- can set the log path of it's dependencies. E.g. cortex js & cpp. Whether or not to split should be configurable.
- can toggle on/off its dependency's cache cleaning mechanism (to avoid side effects)

cc @marknguyen1302  for advice to make cortex.cpp work with Jan, thank you very much

**Comment by dan-menlo** [comment]
Linked to #1153

**Comment by dan-menlo** [comment]
This is a great idea and should be part of `.cortexrc`

**Comment by nguyenhoangthuan99** [comment]
PR #1356 
This is the content of `.cortexrc`:
```
logFolderPath: /home/thuan/cortexcpp
logLlamaCppPath: ./logs/cortex.log
logTensorrtLLMPath: ./logs/cortex.log
logOnnxPath: ./logs/cortex.log
dataFolderPath: /home/thuan/cortexcpp
maxLogLines: 100000
apiServerHost: 127.0.0.1
apiServerPort: 3928
checkedForUpdateAt: 1727660326
latestRelease: v0.5.0
```
Now user can set the log location of each engine, the default location is the same with server `cortex.log`

**Comment by gabrielle-ong** [comment]
Completed
![Image](https://github.com/user-attachments/assets/2c84b62b-564f-4b4e-aa8f-640c5158ee89)
