### ISSUE TITLE
feat: `cortex engines get <engine_id>`

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1073]

**Comment by namchuai** [comment]
I will change this name back to cortex engines get because its purpose is to get an engine status (ready, not ready, etc.)
For `engines <name> install`, please go to https://github.com/janhq/cortex/issues/1072

**Comment by namchuai** [comment]
The PR for this is merged and I think we can move this ticket to QA.

![Image](https://github.com/user-attachments/assets/a466696b-0462-48db-9e70-c014f388dfe4)

HTTP API:
```
curl --location 'localhost:3928/engines/cortex.llamacpp'
```
Response:
```
{
    "description": "This extension enables chat completion API calls using the LlamaCPP engine",
    "name": "cortex.llamacpp",
    "productName": "LlamaCPP Inference Engine",
    "status": "not_initialized",
    "version": "0.0.1"
}
```

**Comment by gabrielle-ong** [comment]
QA: `cortex engines get <engine id>` works 
✅ Mac
✅ Windows
✅ Ubuntu

Linked to follow-up open issue #1168 - to have consistency in the names & IDs
eg `cortex engines get cortex.llamacpp` when the engines list table shows Name = `llama.cpp`

Mac
![Image](https://github.com/user-attachments/assets/db840166-1c28-4ecf-a73d-62273c11fa7f)

Windows:
![Image](https://github.com/user-attachments/assets/e1d9a682-4a42-4762-929f-58673ea6de9b)

Ubuntu:
![Image](https://github.com/user-attachments/assets/f8b6c856-1564-4855-8fde-2f598e82c6b6)
