### ISSUE TITLE
feat: `cortex engines list`

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1074]
command:
`cortex-cpp engines list`

**Comment by nguyenhoangthuan99** [comment]
When building the binary, in window I met a problem that doesn't appear on Linux and Mac:


![Image](https://github.com/user-attachments/assets/3d6e7eb2-5e2d-4c82-9abb-44a1b818efd4)

To resolve this please check  [this commit](https://github.com/janhq/cortex/pull/1050/commits/d33ae7d9052dc358964dec1abbc6943db6e3005b) if you meet this error in the future

**Comment by nguyenhoangthuan99** [comment]
to use commands: 
`./cortex-cpp engines list`

It will show result like this 


![Image](https://github.com/user-attachments/assets/45e1f305-4680-455c-aa0b-8cff52019c72)


The onnx engine'status will be `not_supported` in Linux and Mac. 
and if the engine was found the status will be `ready` otherwise `not_initialized`

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 @vansangpfiev I recommend for us to simplify the `cortex engines list` to a simpler table

| # | Name | Supported Formats | Version | Status | 
|-|-|-|-|-|
| 1 | ONNXRuntime |  ONNX | 0.0.1 | Incompatible |
| 2 | llama.cpp | GGUF | 0.0.1 | ready | 
| 3 | TensorRT-LLM | TensorRT Engines | 0.0.1 | Not installed | 

I personally think the description and product_name is a bit extraneous, should keep this simple

For the TensorRT-LLM supported format, I would need to ask you guys what the "Supported Format" is - .engine files? (not sure)

**Comment by dan-menlo** [comment]
@namchuai Can I reassign this to you, since you are the main owner of `engines` API endpoint and CLI

**Comment by namchuai** [comment]
@dan-homebrew yes, I will work on this. However, I have question regarding the semantic naming for engine which we have a discussion here: https://github.com/janhq/cortex.cpp/issues/1168

**Comment by gabrielle-ong** [comment]
QAed with #1073 (see screenshots there)

Linked to open followup issue on #1168
