### ISSUE TITLE
feat: `cortex models get <MODEL_ID>`  and `cortex models list`

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1075]

**Comment by nguyenhoangthuan99** [comment]
PR: https://github.com/janhq/cortex/pull/1035

**Comment by nguyenhoangthuan99** [comment]
command:
`./cortex-cpp models get <model_id>`
for example:
`./cortex-cpp models get tinyllama`

The command will output all content in the <model_id>.yaml file if it existed.
![image](https://github.com/user-attachments/assets/b384d998-7e24-4ab7-a42d-bc06570121cd)

**Comment by nguyenhoangthuan99** [comment]
Need to update this command to align with #1154
