### ISSUE TITLE
docs: architecture design

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1079]
**Pages**
- Page(s) that need to be done

**Success Criteria**
Content that should be covered

**Additional context**
Examples, reference pages, resources

**Comment by dan-menlo** [comment]
I am going to close this issue; this is an ongoing process that is better handled by "living" Spec pages:

- https://github.com/janhq/cortex.cpp/discussions/1135
- https://github.com/janhq/cortex.cpp/discussions/categories/specs
