### ISSUE TITLE
discussion: https library

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1080]
We are currently using [drogon](https://github.com/drogonframework/drogon), but it has too many dependencies. Should we replace it with [cpp-httplib](https://github.com/yhirose/cpp-httplib)? cpp-httplib supports multiplexing IO, header only, only depends on openssl

Sub-tasks:
- [x] janhq/cortex#1078
- [x] janhq/cortex#1077

**Comment by dan-menlo** [comment]
@vansangpfiev @namchuai I am going to close this issue, as I think we made a decision sometime last week:

- We can focus on documenting the key decisions here: https://github.com/janhq/cortex.cpp/discussions/1133
- Please let me know if I am closing this incorrectly (e.g. if we still need to find a https library)
