### ISSUE TITLE
CI to pack CUDA dependencies for cortex.tensorrt-llm

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1086]
## Overview

- Ref discussion #1046 
- Sub-task of #1072

**Comment by dan-menlo** [comment]
Reassigning to this @namchuai (engines install owner) and @hiento09 (CI owner)

**Comment by hiento09** [comment]
![Image](https://github.com/user-attachments/assets/a26b071b-adb1-43a1-aa65-3b22b19deb08)

**Comment by gabrielle-ong** [comment]
Closing all open Tensorrt-llm stories due to TensorRT-LLM not supporting Desktop
Parent issue: https://github.com/janhq/cortex.cpp/issues/1742
