### ISSUE TITLE
feat: update data folder path

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1121]
We was assuming data folder will be in the same folder as `cortex` binary file
```
cortex
|__ engines
|__ models
|__ cortex.exe
``` 
but we finalized the data folder structure in https://github.com/janhq/cortex.cpp/discussions/1115
This requires us to update logic to make it works properly.

fixes #1154

**Comment by gabrielle-ong** [comment]
Closing this - adding as a sub feat of the bigger epic
