### ISSUE TITLE
bug: Not enough RAM for all models

### ISSUE THREAD

**Issue by CRASH-Tech** [janhq/cortex.cpp#1143]
hi, I ran Jan via docker compose, but all models cannot start "Not enough RAM", but I have 512GB of memory in the server.
![image](https://github.com/janhq/cortex.cpp/assets/13507148/7e6c8631-4c9c-4624-9070-db63f6307ccd)

![image](https://github.com/janhq/cortex.cpp/assets/13507148/0bdecf76-deab-467f-aa29-95952341eff7)

**Comment by dan-menlo** [comment]
We likely need to refactor this into a larger Feature Revamp for "Hardware Detection and Recommendations"

- This issue
- https://github.com/janhq/cortex.cpp/issues/1142

**Comment by ux-han** [comment]
> * bug: CPU and GPU modes - "Slow on your device" #2734

Created epic here: https://github.com/janhq/cortex.cpp/issues/1108

**Comment by ux-han** [comment]
I'll mark this as duplicate & should be a user story of the https://github.com/janhq/cortex.cpp/issues/1108 epic

**Comment by dan-menlo** [comment]
Merging into #1108
