### ISSUE TITLE
feat: Download model directly from HF url

### ISSUE THREAD

**Issue by namchuai** [janhq/cortex.cpp#1145]
**Problem**
Download model directly from Hugging face url

**Success Criteria**
Model is able to download and can be used after download successfully

**Additional context**
https://github.com/janhq/cortex.cpp/issues/1004#issuecomment-2333488224
#1077

**Comment by gabrielle-ong** [comment]
QA:
Without Variants -> triggers variant selection
1. cortex pull <model ID> eg `tinyllama` → from cortexso HF
2. cortex pull <HF repo_id/model_id> eg `TheBloke/Mistral-7B-Instruct-v0.1-GGUF`

With variants
3. cortex pull <Model ID:variant>` eg `tinyllama:gguf` -> from cortexso HF
4. cortex models pull <HF URL> eg `https://huggingface.co/BafS/gemma-2-2b-it-Q4_K_M-GGUF/blob/main/gemma-2-2b-it-q4_k_m.gguf`

✅ Mac
✅ Windows
✅ Linux
