### ISSUE TITLE
epic: Update Cortex Website for v0.1

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1148]
## Goal 

- Website and Github README should reflect updated value proposition for cortex.cpp
- Docs should reflect correct functionality for Cortex

## Tasklist

- [ ] Cortex website changes from @dan-homebrew 
- [ ] Model page
- [ ] KIV all TensorRT-LLM and ONNX stuff

**Comment by urmauur** [comment]
@dan-homebrew, is this ticket a duplicate?

**Comment by dan-menlo** [comment]
Yes - it's a duplicate. Sorry about that, please close
