### ISSUE TITLE
feat: Return logits_prob in `chat_completion`

### ISSUE THREAD

**Issue by hiro-v** [janhq/cortex.cpp#1163]
**Problem**
- Hi, I'm using https://github.com/EleutherAI/lm-evaluation-harness/tree/main to benchmark for `MMLU` and `TruthfulQA`. However currently cortex does not return `logits_prob`

**Success Criteria**

**Additional context**
- `https://github.com/ggerganov/llama.cpp/issues/6285`
- `https://github.com/ggerganov/llama.cpp/issues/6423`

**Comment by dan-menlo** [comment]
@hiro-v Great idea - merged into https://github.com/janhq/cortex.cpp/issues/1151 for Sprint 21
