### ISSUE TITLE
bug: Uninstall instructions for legacy cortexso

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1195]
## Goal 

- We need clear uninstall instructions for users who installed our previous `cortex-js` 
- This should be a Docs page that we can quickly send to users 

## Tasklist

- [ ] Remove all old files from users computers
- [ ] Multiple OS instructions (e.g. Windows, Mac, Linux)

**Comment by dan-menlo** [comment]
@louis-jan @hiento09 I'm taking a stab at this - can you take a look and see if I'm missing anything?

Legacy Installation Formats:

```
# npm
npm uninstall -g cortexso

# Mac
brew uninstall cortexso

# Windows
winget uninstall cortexso

# Linux
apt remove cortexso
```

**Comment by louis-jan** [comment]
@dan-homebrew @hiento09 That looks correct.

There is another legacy, deprecated package that we delivered a long time ago (removed from the npm repository):

```
### npm (@janhq/cortex)
npm uninstall -g @janhq/cortex
```

Windows Installer
```
### Windows Installer
- Select Start > Settings > Apps > Apps & features > Cortex
```

Use the `which` command to find if there is somehow a cortex binary still existing
```
# Unix: `which cortex`
# Windows: `where cortex`

Example: 
$ which cortex
/opt/homebrew/bin/cortex
```
On Windows, it's better to make sure that users updated $PATH to remove the existing Cortex PATH environment variable.

**Comment by dan-menlo** [comment]
> @dan-homebrew @hiento09 That looks correct.
> 
> There is another legacy, deprecated package that we delivered a long time ago (removed from the npm repository):
> 
> ```
> ### npm (@janhq/cortex)
> npm uninstall -g @janhq/cortex
> ```
> 
> Windows Installer
> 
> ```
> ### Windows Installer
> - Select Start > Settings > Apps > Apps & features > Cortex
> ```
> 
> Use the `which` command to find if there is somehow a cortex binary still existing
> 
> ```
> # Unix: `which cortex`
> # Windows: `where cortex`
> 
> Example: 
> $ which cortex
> /opt/homebrew/bin/cortex
> ```
> 
> On Windows, it's better to make sure that users updated $PATH to remove the existing Cortex PATH environment variable.

Thanks @louis-jan!

**Comment by gabrielle-ong** [comment]
![Image](https://github.com/user-attachments/assets/2522ace6-0da0-49c8-a350-24e5f50127ac)
I npm uninstalled cortex, but still have the dangling cortex folder remaining - exact scenario described in #1082 
Does it require manual deletion of the cortex folder? @louis-jan

**Comment by louis-jan** [comment]
> ![Image](https://github.com/user-attachments/assets/2522ace6-0da0-49c8-a350-24e5f50127ac) I npm uninstalled cortex, but still have the dangling cortex folder remaining - exact scenario described in [#1082](https://github.com/janhq/cortex.cpp/issues/1082) Does it require manual deletion of the cortex folder? [@louis-jan](https://github.com/louis-jan)

What a nice catch. @gabrielle-ong I'm scared to delete the user Cortex folder, but we should mention that they should do themselves in the uninstallation docs. Also, try adding a section to ask them to run `cortex stop` before uninstalling would be great.

**Comment by dan-menlo** [comment]
Marking this as completed
