### ISSUE TITLE
epic: `cortex` command to start server has useful helper text

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1226]
## Goal 

- `cortex` command starts server
- `cortex` command should show server running at certain port
- `cortex` command should dump errors if occur (e.g. port conflict)
- `cortex` command should show common commands (and tell user to run `-h` if they want to see full list)
- `cortex` command should show some ASCII art, i.e. "Cortex"

## Resources

- https://github.com/janhq/cortex.cpp/discussions/1109#discussioncomment-10635406

Oh-my-zsh
![Image](https://github.com/user-attachments/assets/f7d83978-d7e7-4ff1-baac-59ffa8a1e2b6)

Docker's example
![Image](https://github.com/user-attachments/assets/a9905b03-7daa-4fa1-b4a3-bd8b4958ddd7)

**Comment by dan-menlo** [comment]
@vansangpfiev I am tagging this to you in Sprint 20; however I see this as a mostly cosmetic change and you should focus on core functionality before working on this.

**Comment by dan-menlo** [comment]
@vansangpfiev I believe this epic is implemented already, do you mind linking the PRs that close it (or the issues that superseded it) and then proceed to close? 

e.g.:
- #1235 
- #1231

**Comment by gabrielle-ong** [comment]
Marking as complete, thanks @vansangpfiev
