### ISSUE TITLE
feat: `cortex -h` should have commands categorized

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1231]
## Goal 

- Our CLI `-h` should have categories for commands, for easier understanding
- Additionally, are we able to have submodules, that also have their own `-h`? (e.g. `cortex models -h`)

```
Cortex.cpp CLI
Usage: cortex-nightly [OPTIONS] [SUBCOMMAND]

Options:
  -h,--help                   Print this help message and exit
  --verbose                   Verbose logging
  -v                          Cortex version

Common Commands:
  pull                        Download model from Huggingface or Cortex repo  
  run                         Shortcut to start a model and chat
  chat                        Send a chat request to a model

Inference:
  embeddings                  Creates an embedding vector representing the input text

Models:
  models                      Subcommands for managing models
  models pull

Engines:
  engines                       Get cortex engines
  engines install 
  engines uninstall

System: 
  start                        Starts Cortex
  stop                        Stop Cortex
  update                      Update cortex to the latest version
  ps                          Show running models and their status
```

## Resource

Docker is a good example of how commands can be categorized

![Image](https://github.com/user-attachments/assets/fbd88ac4-da45-4d3f-af3d-76ab643dc8f5)

**Comment by vansangpfiev** [comment]
> ## Goal
> * Our CLI `-h` should have categories for commands, for easier understanding
> * Additionally, are we able to have submodules, that also have their own `-h`? (e.g. `cortex models -h`)
> 
> ```
> Cortex.cpp CLI
> Usage: cortex-nightly [OPTIONS] [SUBCOMMAND]
> 
> Options:
>   -h,--help                   Print this help message and exit
>   --verbose                   Verbose logging
>   -v                          Cortex version
> 
> Common Commands:
>   pull                        Download model from Huggingface or Cortex repo  
>   run                         Shortcut to start a model and chat
>   chat                        Send a chat request to a model
> 
> Inference:
>   embeddings                  Creates an embedding vector representing the input text
> 
> Models:
>   models                      Subcommands for managing models
>   models pull
> 
> Engines:
>   engines                       Get cortex engines
>   engines install 
>   engines uninstall
> 
> System: 
>   start                        Starts Cortex
>   stop                        Stop Cortex
>   update                      Update cortex to the latest version
>   ps                          Show running models and their status
> ```
> 
> ## Resource
> Docker is a good example of how commands can be categorized
> 
> ![Image](https://private-user-images.githubusercontent.com/101145494/367981841-fbd88ac4-da45-4d3f-af3d-76ab643dc8f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDEyMzcsIm5iZiI6MTcyNjU0MDkzNywicGF0aCI6Ii8xMDExNDU0OTQvMzY3OTgxODQxLWZiZDg4YWM0LWRhNDUtNGQzZi1hZjNkLTc2YWI2NDNkYzhmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwMjQyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWU1Y2YwOWUxNjAzNjNlODdhOTFjZjNhOTBiZWEwM2E5NDk4MWUzMTRjM2FkNGNiMGVhN2M5OTA4YjcxZTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FBBcNe0MnhKity0lBp_aMZAU9uNfm5jYH7zwU72gWQA)

```
Our CLI -h should have categories for commands, for easier understanding
```
I agree. This is a great improvement we should have. However, it may take time because we are using `CLI11` default output for CLI, so maybe will need a workaround.
I will take a look on it after ensure all the functional features work.

```
Additionally, are we able to have submodules, that also have their own -h? (e.g. cortex models -h)
```
Yes, we are. 

![image](https://github.com/user-attachments/assets/61ede4a9-1665-4e41-bd4d-f28270ef77b2)

**Comment by dan-menlo** [comment]
Thanks @vansangpfiev. I am tagging this to Sprint 20 scope, and we can push it to 21 if not possible.
