### ISSUE TITLE
feat: `cortex start`

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1232]
## Goal

- We should have a clear `start` command, which takes port number
- This should differentiate from `cortex`, which should be more similar to `-h` and also show where data is persisted

## Clarifications needed

- Is `cortex start` a pre-requisite to `cortex run`? 
- `cortex run` should automatically start a server if it is not already running

## Tasklist

- [x] #1234

**Comment by vansangpfiev** [comment]
```
Is cortex start a pre-requisite to cortex run?
```
Yes, it is
```
cortex run should automatically start a server if it is not already running
```
We don't start server automatically yet, will add it soon

@dan-homebrew I think `cortex start` change is reasonable. Let me take a stab at it. However
```
This should differentiate from cortex, which should be more similar to -h and also show where data is persisted
```
this change may take time, so will work on `cortex start` first

**Comment by dan-menlo** [comment]
> ```
> Is cortex start a pre-requisite to cortex run?
> ```
> 
> Yes, it is
> 
> ```
> cortex run should automatically start a server if it is not already running
> ```
> 
> We don't start server automatically yet, will add it soon
> 
> @dan-homebrew I think `cortex start` change is reasonable. Let me take a stab at it. However
> 
> ```
> This should differentiate from cortex, which should be more similar to -h and also show where data is persisted
> ```
> 
> this change may take time, so will work on `cortex start` first

Got it, thank you @vansangpfiev

**Comment by vansangpfiev** [comment]
Resolved by https://github.com/janhq/cortex.cpp/issues/1234
