### ISSUE TITLE
docs: Sprint 21 docs updates

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1243]
## Structure

One idea for Docs is: 

```
# GET STARTED
Overview
Quickstart (should be expanded, and link to most other sections)
Installation

# BASIC USAGE
Overview (should emphasize API server usage)
.cortexrc
model.yaml
Data Folder (covers where Cortex stores its files)
/libraries
    cortex.js
    cortex.py
/Model Sources
    Huggingface
    Cortex Hub
/Engines
    llama.cpp
    TensorRT-LLM
    ONNX

# CLI
...
```

## Tasklist 

- [ ] Install and Uninstall instructions
    - https://github.com/janhq/cortex.cpp/discussions/1114
    - https://github.com/janhq/cortex.cpp/issues/1030

- [ ] Cortex Data Structures
    - https://github.com/janhq/cortex.cpp/discussions/1115#discussioncomment-10558481

- [ ] `.cortexrc`
    - What fields are in `.cortexrc`?
    - https://github.com/janhq/cortex.cpp/issues/1031

- [ ] Stable, Beta and Nightly Builds
    - https://github.com/janhq/cortex.cpp/issues/1065
    - Need to document how we have different commands, data structures foe each ones

- [ ] `llama.cpp` Params:
    - https://github.com/janhq/cortex.cpp/issues/1151
    - @nguyenhoangthuan99 

- [ ] Model Folder + `model.yaml`
    - https://github.com/janhq/cortex.cpp/issues/1154
    - @nguyenhoangthuan99 

- [ ] Logs: where do they go
    - https://github.com/janhq/cortex.cpp/issues/1153
    - @nguyenhoangthuan99 

- [ ] Models list now maintained in Sqlite (prev models.list)
- https://github.com/janhq/cortex.cpp/pull/1336#issuecomment-2378440047

- [ ] Network installer vs Local installer

**Comment by irfanpena** [comment]
@dan-homebrew For Beta and Nightly version, I am not really sure that we should also provide commands for each version, as the users supposedly and encouraged to use the Stable version.

**Comment by dan-menlo** [comment]
@gabrielle-ong I am transferring this issue to you for Sprint 21, please review existing PRs and merge it to https://cortex.so.
