### ISSUE TITLE
bug: `cortex update` fails, `filesystem error: Text File busy` (Linux)

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1311]
### Cortex version

0.5.0-82

### Describe the Bug

Linux Ubuntu - 22.04.5 LTS

`cortex update` fails, returns:
`Something went wrong: filesystem error: cannot copy file: Text file busy [tmp/cortex/cortex-nightly] [usr/bin/cortex-nightly]`

### Screenshots / Logs

![Screenshot 2024-09-23 at 6 30 39 PM](https://github.com/user-attachments/assets/c1d65956-3dee-4750-ad6b-d163631d62bf)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by vansangpfiev** [comment]
Can you try with `sudo`? For Linux we need permissions to access /user/bin/

Vào 17:34, Th 2, 23 thg 9, 2024 Gabrielle Ong ***@***.***> đã
viết:

**Comment by vansangpfiev** [comment]
From `v0.5.0-92`, cortex will output a message if user does not `cortex update` on Linux and macOS
```
Error: Not root user. Please run with sudo.
```
cc: @gabrielle-ong

**Comment by gabrielle-ong** [comment]
Yes, sudo works - thanks for error handling! will close this issue and validate on v92
![image](https://github.com/user-attachments/assets/d06545cf-a6a5-46aa-8e1f-b8eae85e56e0)
