### ISSUE TITLE
feat: models delete with new model folder structure

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1320]
fixes #1154

**Comment by gabrielle-ong** [comment]
@sangjanai Edited:
Qn: Do we expect to delete the folder that contains the .gguf and .yml file?
- If there are multiple models in the same folder (when is this the case?) - then we want to delete the files but not the folder

1.`cortex models delete tinyllama`
2. ✅ `cortex models list` doesnt have deleted model
3. ❌ .gguf and .yml file is deleted, but not the parent folder eg 1b-gguf
![Image](https://github.com/user-attachments/assets/71059251-aa9d-4f99-9f62-cb1f69ddf2a8)

**Comment by vansangpfiev** [comment]
We do not delete model folder because we can have several models in the same directory.
![image](https://github.com/user-attachments/assets/bdf5bc63-e9e9-447f-8311-446b6dea3faf)
@gabrielle-ong

**Comment by gabrielle-ong** [comment]
Noted. Ok, marking as closed, .gguf and .yml files deleted as expected
QA: Windows, Mac, Ubuntu
