### ISSUE TITLE
Add requests and response body to log in DEBUG mode

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1323]

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 Is this task still necessary?

**Comment by nguyenhoangthuan99** [comment]
- We need to add log request and response body with DEBUG log level.
- We need to support set loglevel when start cortex server:
     - `cortex start --loglevel DEBUG`.
     - List of accepted loglevel is: `TRACE`, `DEBUG`, `INFO`, `WARNING`, `ERROR`

**Comment by gabrielle-ong** [comment]
Thanks @nguyenhoangthuan99 for the note:
ERROR > WARN > INFO > DEBUG > TRACE. for example if you set log level is INFO you'll only see ERROR, WARN, and INFO

On Mac, I'm still getting INFO logs despite setting WARN loglevel.
```
cortex stop
cortex start --loglevel WARN
cortex run tinyllama:1b-gguf
```
Here's the new log files (after deleting)
[cortex-cli.log](https://github.com/user-attachments/files/17715119/cortex-cli.log)
[cortex.log](https://github.com/user-attachments/files/17715120/cortex.log)

**Comment by gabrielle-ong** [comment]
@vansangpfiev thanks for fixing! 
✅ QA: The correct priority of log levels appear for Mac: ERROR > WARN > INFO > DEBUG > TRACE
