### ISSUE TITLE
bug: Model download fails due to `YAML::BadFile`

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1325]
### Cortex version

v94

### Describe the Bug

Linux 22
VM: ubuntu app 1

see screenshot:
1. `cortex run tinyllama` is successful

2. `cortex run tinyllama:gguf` 
- fails to download model
- fail to read file, error bad file

4. `cortex run llama3.1` -> select gguf option
- Failed to download, but then also `Model downloaded successfully` (separate issue filed)
- bad yaml file

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/572c8049-6b51-47d3-980c-1cf6b5a0f660)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
![Image](https://github.com/user-attachments/assets/e5e5b5e1-c1c1-47ae-95df-991d02b8238d)

I am getting this YAML::BadFile error for `cortex models stop`

**Comment by vansangpfiev** [comment]
Should be resolved by `v0.5.0-125`. @gabrielle-ong Could you please have a try?

**Comment by gabrielle-ong** [comment]
v129 - marking as complete, no issues encountered with `cortex run` and `cortex models stop`
