### ISSUE TITLE
chat with mistral nemo return empty message

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1338]
**Problem**
When import any `mistral-nemo` model, chat always return empty message from assistant
![Image](https://github.com/user-attachments/assets/289dd9be-7b05-4b2b-bfeb-49bb3b179224)

The root cause is the prompt template is generated improperly.
The current generated prompt template is 
```
[INST] {system_message}\n{prompt} [/INST]
```

The correct prompt template should be
```
[INST] {system_message}\n[INST] {prompt} [/INST]
```

**Solution**

Update the render chat template logic to handle this case

After update chat template renderer, can chat with Mistral nemo successfully

![Image](https://github.com/user-attachments/assets/dbef6b54-82fc-4d0c-afa9-0c7a2fd81074)

Related issue janhq/models#19

**Comment by gabrielle-ong** [comment]
QA - Mistral nemo works for Mac, Ubuntu
✅ Mac
![Image](https://github.com/user-attachments/assets/fa181dd4-ab4d-4564-8e39-997815872ea3)

✅ Ubuntu
![Image](https://github.com/user-attachments/assets/e6f15a78-173e-493b-8ae0-03323ef6f0e2)

✅ Windows
![Image](https://github.com/user-attachments/assets/ce6e5fa5-f2da-42f6-9942-5372da923bdf)
