### ISSUE TITLE
bug: check new update hang if network is down

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1350]
### Cortex version

v0.5.0-120

### Describe the Bug

Check new update for will be hanged if network is down

### Steps to Reproduce

run `cortex -v`

### What is your OS?

- [ ] MacOS
- [X] Windows
- [X] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
![Image](https://github.com/user-attachments/assets/4fb620ac-3bee-4da6-86e0-88a379ed2bc9)

@vansangpfiev is this what we expect for this issue?
- Y Doesnt hang 
- But errors something went wrong cannot copy file (this shouldnt be triggered)

**Comment by vansangpfiev** [comment]
@gabrielle-ong It is expected, because the download binary does not exist. 
However, it can be improved, we should not try to update binary if download failed.

Update: the download binary does exist but it is empty, so the logic is correct in this case.
