### ISSUE TITLE
feat: use relative path for model info in data folder

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1368]
We store absolute path for `yaml` path in database. When we transfer the Cortex data folder (models) to another computer or move it between disks/folders, it will break.
We have all model data in the data folder, it makes sense to store relative path in the database.
Note: we have an edge case for `import` model

Motivation / context: https://discordapp.com/channels/1107178041848909847/1204617960615055401/1290493569156776088

**Comment by gabrielle-ong** [comment]
@vansangpfiev do we have an issue tracking the edge case for import models?

**Comment by vansangpfiev** [comment]
@gabrielle-ong  Created a ticket for tracking: https://github.com/janhq/cortex.cpp/issues/1496

**Comment by gabrielle-ong** [comment]
QA: Mac, Linux, Windows
✅ Successfully transfer models across folders and disks

**Comment by gabrielle-ong** [comment]
@vansangpfiev clarifying so I can understand this better for docs (no changes needed for v1.0.1)
1. When is the case that users will copy model data folders (is this an edge case or do we want to encourage it?)

2. My understanding is that generally if users copy a model folder in, they will still have to run `cortex pull` to load the model into cortex.db, is that correct? 

## Sample test (this may be entirely wrong, cmiiw)
![Image](https://github.com/user-attachments/assets/7b2d1563-418b-489c-b84b-9da63dd0a83e)

![Image](https://github.com/user-attachments/assets/bf66061c-b4da-4637-993b-7144dc0ed1fa)

For this screenshot, I copied a new `models` folder and renamed the old one `archived_models`
3. Filed to read file: bad file (this is because it is not yet loaded to db?)
4. pull huggingface with model ID `TheBloke` - failed - why?
5. pull cortexso `tinyllama` - exists in the model folder, but retriggers download - why?

**Comment by vansangpfiev** [comment]
@gabrielle-ong This PR is intended for migrating all cortex data folder which includes `models` `engines` and `cortex.db`

**Comment by dan-menlo** [comment]
@gabrielle-ong I think this PR isn't supposed to cover the "model import" edge case - e.g. copying a model folder in. 

@vansangpfiev is just updating Cortex to use relative paths instead of absolute paths. I think we can handle the import scenario in the separate ticket.

> @vansangpfiev clarifying so I can understand this better for docs (no changes needed for v1.0.1)
> 
> 1. When is the case that users will copy model data folders (is this an edge case or do we want to encourage it?)
> 2. My understanding is that generally if users copy a model folder in, they will still have to run `cortex pull` to load the model into cortex.db, is that correct?
> 
> ## Sample test (this may be entirely wrong, cmiiw)
> ![Image](https://private-user-images.githubusercontent.com/17236572/378799204-7b2d1563-418b-489c-b84b-9da63dd0a83e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDI1MjEsIm5iZiI6MTcyOTYwMjIyMSwicGF0aCI6Ii8xNzIzNjU3Mi8zNzg3OTkyMDQtN2IyZDE1NjMtNDE4Yi00ODljLWI4NGItOWRhNjNkZDBhODNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEzMDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OTkxNDZkMGQ3Zjk0NzA0Y2M5ZTEzZTkzN2U2ZTljODcwOWE4Mzk4ZTMyNWUzYzg0NjZmNzZiNWI3NGVkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pdV12uiQE9l8l_OiUpqD_4VNzg2bphUerkM8IThNV0I)
> 
> ![Image](https://private-user-images.githubusercontent.com/17236572/378800002-bf66061c-b4da-4637-993b-7144dc0ed1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDI1MjEsIm5iZiI6MTcyOTYwMjIyMSwicGF0aCI6Ii8xNzIzNjU3Mi8zNzg4MDAwMDItYmY2NjA2MWMtYjRkYS00NjM3LTk5M2ItNzE0NGRjMGVkMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEzMDM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYTcxNjg4YmMwZGMyMThlNDFjNWJjNGUwMmU3ODI1YzE2NmE3MTNlNmNiNzQwMzE0Njk3OTcwYjQ1ZTRiZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ImY4gE5CuBOsNGCU6dUq6NUfMqAPvpV0JlBpRsxMpk)
> 
> For this screenshot, I copied a new `models` folder and renamed the old one `archived_models` 3. Filed to read file: bad file (this is because it is not yet loaded to db?) 4. pull huggingface with model ID `TheBloke` - failed - why? 5. pull cortexso `tinyllama` - exists in the model folder, but retriggers download - why?
