### ISSUE TITLE
bug: No engine field in request body

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1372]
### Problem Statement

I'm sending a chat/completions request to the cortex.cpp endpoints, setting up my daily use tools. The request is fully OpenAI compatible. I always receive an error response similar to this:

```json
{
    "message": "No engine field in request body"
}
```

### Feature Idea

Since the cortex.cpp manages to retrieve model information, it should select the engine accordingly. This eliminates the need for an extra `engine` field in the request, ensuring that 100% OpenAI-compatible products can utilize the endpoint.

**Comment by louis-jan** [comment]
It always returns an empty response, regardless of how I modify the request body.

**Comment by gabrielle-ong** [comment]
@louis-jan can I verify this PR fixes this issue? cc @vansangpfiev

**Comment by louis-jan** [comment]
Hi @gabrielle-ong, I tested the latest version, and it works now.

![97727](https://github.com/user-attachments/assets/b7387df6-e4ef-4dc9-a222-0694228f777c)
