### ISSUE TITLE
Jan erroring out when trying to JSON

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1389]
Context:
https://discordapp.com/channels/1107178041848909847/1288196081280356362/1288196081280356362

```
curl -X POST 'http://127.0.0.1:1337/v1/chat/completions' -H "authorization: Bearer whatever" -H "content-type: application/json" -d "{
  \"temperature\": 0.3,
  \"model\": \"Meta-Llama-3.1-8B.Q5_1.gguf\",
  \"messages\": [
    {
      \"role\": \"system\",
      \"content\": [
        {
          \"type\": \"text\",
          \"text\": \"Validate the following business information.\n\nAnswer in JSON using this schema:\n{\n  address: {\n    locality: string,\n    // 2 characters long\n    region: string,\n    // must be 5 characters long\n    postal: string,\n    street: string,\n  },\n  name: string,\n  // Format: 'Day(s) OpenTime-CloseTime', e.g., 'Mo-Fr 09:00-17:00'.\n  // ensure the opening time is before the closing time.\n  openingHours: string[],\n  phone: string,\n  fax: string,\n  // must be valid email\n  email: string,\n  // valid url format\n  website: string,\n}\n\nBUSINESS_INFO:\nhello world\"
        }
      ]
    }
  ],
  \"stream\": true,
  \"stream_options\": {
    \"include_usage\": true
  }
}"
```

**Comment by gabrielle-ong** [comment]
Moving to Sprint 23 as part of Structured Outputs - to align with OpenAI Structured Output https://platform.openai.com/docs/guides/structured-outputs

**Comment by dan-menlo** [comment]
@vansangpfiev Can you paste the relevant Docs from OpenAI API Docs here, so @gabrielle-ong can cover this in Docs

**Comment by vansangpfiev** [comment]
https://platform.openai.com/docs/api-reference/chat/create
![image](https://github.com/user-attachments/assets/79335aed-a27e-4b46-8a94-a3f78647d4d9)

We need to support both string and array type for the `content`

**Comment by gabrielle-ong** [comment]
thank you @vansangpfiev!
✅ QA: v222
API request: v1/chat/completions
Content takes in an array
![Image](https://github.com/user-attachments/assets/8ed573c2-48e1-480d-96d7-3e11faa184ae)

Docs updated by Sang
![Image](https://github.com/user-attachments/assets/d89e69f3-d1ab-4f67-8d8c-8a50b4d1ad81)
