### ISSUE TITLE
idea: [DownloadEvent] Adding websocket to publish download event to client

### ISSUE THREAD

**Issue by namchuai** [janhq/cortex.cpp#1393]
### Problem Statement

- Currently we don't send any event to client. So, client can't update UI accordingly.
- Drogon does not support SSE.

### Feature Idea

- Publishing events via websocket at `ws://127.0.0.1:3928/events`

**Comment by namchuai** [comment]
PR merged, closed!

**Comment by gabrielle-ong** [comment]
QAing as overall of #1242, marking as complete
- web sockets events emitted when model pull starts `/events`
- web sockets events stopped when model pull stops `/events`
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/90b261fa-f7b9-4f7c-a5b5-74318698e920">
