### ISSUE TITLE
idea: [DownloadEvent] Adding event queue to process event asynchronously

### ISSUE THREAD

**Issue by namchuai** [janhq/cortex.cpp#1394]
### Problem Statement

If we write a simple callback, the thread of event emitter will have to wait for the event listener to finished consuming events. This might cause hang.

### Feature Idea

Using [eventpp package](https://vcpkg.link/ports/eventpp) to have an `EventQueue` which acts as a buffer in between `EventEmitter` and `EventListener`

**Comment by namchuai** [comment]
PR merged, closed!

**Comment by gabrielle-ong** [comment]
QAing in overall #1242, marking as complete
