### ISSUE TITLE
idea: [DownloadEvent] Wiring up event library and download service

### ISSUE THREAD

**Issue by namchuai** [janhq/cortex.cpp#1395]
### Problem Statement

Wiring up event library and download service

### Feature Idea

- Define reusable events (DownloadEvent, ModelEvent, HardwareEvent, etc.)
- Define an easy API to publish those events
- Broadcast events via websocket

**Comment by namchuai** [comment]
PR merged, closed!

**Comment by gabrielle-ong** [comment]
QA in overall #1242, marking as complete
