### ISSUE TITLE
feat: build macos universal for binary and installer

### ISSUE THREAD

**Issue by hiento09** [janhq/cortex.cpp#1396]
# Description:

We need to enhance our build process to support macOS universal binaries and installers. This will ensure compatibility across both Intel (x86_64) and Apple Silicon (arm64) architectures.

# Requirements:

- Build the macOS universal binary (combining x86_64 and arm64 architectures) for the application.
- Modify the installer to include the universal binary, ensuring it can run on both Intel and Apple Silicon machines.
- Update the CI pipeline to automatically build the macOS universal binary and installer as part of the release process.

# Acceptance Criteria:
- The application should run natively on both Intel and Apple Silicon Macs.
- The installer should properly detect the architecture and install the universal binary.
- Verify that the build process is integrated into the CI pipeline and functions as expected.

# Additional Notes:
- Test on both Intel and Apple Silicon Macs to ensure compatibility.

**Comment by hiento09** [comment]
We need to modify the macOS updater source code and test it as well cc @vansangpfiev @dan-homebrew @gabrielle-ong

**Comment by hiento09** [comment]
Include @vansangpfiev here for the macOS updater source code change.

**Comment by dan-menlo** [comment]
@hiento09 FYI, for `154`, I ran the Universal installer. However, when running a model, encountered the following error:

![Image](https://github.com/user-attachments/assets/bf7c71c7-a9ac-415d-ad6b-0d24af37187b)

![Image](https://github.com/user-attachments/assets/3cf71aca-33fa-4516-9749-32a60af141ff)

**Comment by hiento09** [comment]
> @hiento09 FYI, for `154`, I ran the Universal installer. However, when running a model, encountered the following error:
> 
> ![Image](https://private-user-images.githubusercontent.com/101145494/373504327-bf7c71c7-a9ac-415d-ad6b-0d24af37187b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMTc0NDUsIm5iZiI6MTcyODAxNzE0NSwicGF0aCI6Ii8xMDExNDU0OTQvMzczNTA0MzI3LWJmN2M3MWM3LWE5YWMtNDE1ZC1hZDZiLTBkMjRhZjM3MTg3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQwNDQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjQ1MzNiMDYxYWNmMjViNTM1YWY4ZWYxMWYwNGU3NjljOGUxODg1MDA3ODQwMGRmMjk3OWY1Zjc1YTRiNzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T759Osl_-1D2p3mGXd5Idj5lTkhZG02gPPPrAVq_Xn4)
> 
> ![Image](https://private-user-images.githubusercontent.com/101145494/373504297-3cf71aca-33fa-4516-9749-32a60af141ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMTc0NDUsIm5iZiI6MTcyODAxNzE0NSwicGF0aCI6Ii8xMDExNDU0OTQvMzczNTA0Mjk3LTNjZjcxYWNhLTMzZmEtNDUxNi05NzQ5LTMyYTYwYWYxNDFmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQwNDQ1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjlhYzIwZWI2NmY3YmQzNWFkOTI1MWE1NmM4M2YzNTkyMDE5NjVjYzE5MGVlZmI2OGE0YTY3MGQzYzJjNTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P8ei8Ogxtf8m6GiIYA3RfOo-swBm0onVAb0LDoWj3QM)

@dan-homebrew  can I check how you installed version 154 nightly? I just tried the following scenarios for Mac silicon and Mac intel and they all succeeded:
- Fresh install using the local installer universal
- Fresh install using the network installer universal
- Update from an older version before the Mac universal version existed

**Comment by hiento09** [comment]
I just tried a scenario as follows and encountered a similar issue to what you mentioned:

- My machine is a Mac Silicon
- I downloaded version 152, but the mac amd64 version – it still installed because my machine has Rosetta, but at this point, the llamacpp engine installed is the amd64 variant, which causes it to not run on Mac Silicon.
- I ran cortex update to download version 154 universal and tried running cortex chat tinyllama:1b-gguf.

**Comment by gabrielle-ong** [comment]
@hiento09 I'm closing this issue as the mac Universal installer is complete. Thank you! 🎉 
Tracking this bug in a separate issue: #1422
