### ISSUE TITLE
bug: Failed to read file: bad file ... Q4_K_M.yml

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1413]
### Cortex version

v0.5.0-141

### Issue:
I think I accidentally deleted a model while cleaning my disk with GrandPerspective. Since then, I haven't been able to list out the pulled models.

### Expected: 
The broken model should be disregarded, and other available models are still visible.

![Screenshot 2024-10-03 at 19 58 11](https://github.com/user-attachments/assets/f3f9a5e4-82fc-4b6f-9ed4-c8b46a6987e4)

### Steps to Reproduce

1. Delete any pulled model
2. Run models list
3. See error

### Screenshots / Logs

![Screenshot 2024-10-03 at 19 58 11](https://github.com/user-attachments/assets/f3f9a5e4-82fc-4b6f-9ed4-c8b46a6987e4)

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
QAed on Mac ✅
