### ISSUE TITLE
bug: `Model failed to load with status code: 500`, `could not load engine llamacpp`

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1422]
## Goal

- A lot of useful error messages are currently not being bubbled up to CLI
- We should bubble up as many error messages, to allow users to file more informative bugs or know what is going on

## Current State

Running llama3.1 failed with model status code 500:

![Image](https://github.com/user-attachments/assets/0a6d9ed0-7353-496d-8dea-588b9296c9f5)

The real error message is in the logs:

![Image](https://github.com/user-attachments/assets/29f857b9-6065-480b-970b-52ebd74bd3bf)

**Comment by gabrielle-ong** [comment]
v154 - also getting this error 
<img width="1365" alt="image" src="https://github.com/user-attachments/assets/95ed050a-11e2-4ca8-bf22-499710c8991d">

## Workaround 
```
cortex engines install llama-cpp
```
which should have been pre-installed.  

<img width="836" alt="image" src="https://github.com/user-attachments/assets/253086e3-d81f-4146-a597-479bea514702">

cc @Hiento09 - discord discussion

**Comment by gabrielle-ong** [comment]
should be solved by #1369?

**Comment by gabrielle-ong** [comment]
Copying's Hien's post from #1396 

> I just tried a scenario as follows and encountered a similar issue to what you mentioned:
My machine is a Mac Silicon
I downloaded version 152, but the mac amd64 version – it still installed because my machine has Rosetta, but at this point, the llamacpp engine installed is the amd64 variant, which causes it to not run on Mac Silicon.
I ran cortex update to download version 154 universal and tried running cortex chat tinyllama:1b-gguf.

**Comment by gabrielle-ong** [comment]
Proposal: Investigating -> Feature (high pain) -> Eng Planning

- original bug should be fixed, possibly same error as #1474
- Task remains as a eng task: Useful error messages eg 402, 500 are not being bubbled up to CLI

**Comment by gabrielle-ong** [comment]
Decision from Dan / Nicole:
- new Epic: bubble up error messages from Engines, highlight important error messages
- Status: planning, Eng Spec: Planning, Sprints: 24/25

**Comment by gabrielle-ong** [comment]
Closing this bug as resolved,
creating a separate discussion for bubbling error logs #1514
