### ISSUE TITLE
epic: Cortex has a better CLI UI for downloading

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1423]
## Goal 

- We should have a better CLI UI for downloading progress
- We are currently using the libcurl default, which may be confusing to users used to Github or Docker
- We need to think of this from first principles (i.e. does not map onto Github, Docker or even Ollama's current UX may not be correct)

## Task list
- [x] #1492

## Inspirations

Github has a status indicator (for objects)
- Models tend to not have many objects, just several large ones
![Image](https://github.com/user-attachments/assets/a406f255-ea7a-4e08-962f-b5b64f19aa6e)

Docker pulls layers (shows progress while layer is downloading)
- Models do not have "layers"
![Image](https://github.com/user-attachments/assets/3135bc12-1cee-48c0-85e1-e7215107a17b)

Ollama has a progress bar
- Similar to Docker, they use layers (vs. our approach with normal GGUF files)
![Image](https://github.com/user-attachments/assets/d98bae68-0a5f-44b1-8b57-eaaaf800ef41)

**Comment by vansangpfiev** [comment]
@dan-homebrew I would like to propose a new CLI UI for downloading as below:
![image](https://github.com/user-attachments/assets/d15b00dc-6215-4d2b-ab92-4ee1e727ebe7)
Cortex will show the file names, download progress (both percentage and downloaded/total bytes, time remaining).
How do you think?

**Comment by dan-menlo** [comment]
@vansangpfiev This looks good and a clear improvement. Questions:

- Will it download each file in parallel or sequential?
- Is there a CLI Library that we can use for this? 

Thank you for optimizing for UX.

**Comment by vansangpfiev** [comment]
> @vansangpfiev This looks good and a clear improvement. Questions:
> 
> * Will it download each file in parallel or sequential?
> * Is there a CLI Library that we can use for this?
> 
> Thank you for optimizing for UX.

@dan-homebrew 
- Basically, CLI requests the Server to download a model and open a websocket to pull the progress.
Server supports download files in parallel (thanks @namchuai)
- For progress indicators, I think can use https://github.com/p-ranav/indicators (MIT License)

**Comment by vansangpfiev** [comment]
Unicode char set does not work well on Windows, so we need to simplify the UI a little bit
![image](https://github.com/user-attachments/assets/0c603935-a6e5-41ef-a3b5-0e05d795c73e)
This progress bar is similar to `wget`

**Comment by gabrielle-ong** [comment]
Thanks Sang! Marking as complete

QA: ✅ v1.0.1-218
Mac:
![Image](https://github.com/user-attachments/assets/af91b75f-84bd-4586-8a89-7ea46990a3f1)
![Image](https://github.com/user-attachments/assets/45a5a920-e8b4-46c1-b4f4-5340d71e3c8d)

Windows:
![Image](https://github.com/user-attachments/assets/450d0aca-7545-4647-8514-c9cf07d46349)
![Image](https://github.com/user-attachments/assets/cd74ad30-5eb5-4b21-aab2-349d74a98960)

Linux:
![Image](https://github.com/user-attachments/assets/b92c4eb3-1230-4d77-a948-f4472a22bfae)

**Comment by dan-menlo** [comment]
@gabrielle-ong @vansangpfiev Can you link the PR for this issue, for better discoverability in future
