### ISSUE TITLE
feat: Streamlining `cortex run` behavior

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1425]
## Goal

- We will align with Docker on `cortex run`
    - https://docs.docker.com/engine/containers/run/#foreground-and-background
- We will deprecate `cortex chat`

## Spec

```sh
# `cortex run`
# default: runs attached
cortex run <model>  
cortex run <model>  -a --attached                          
cortex run <model>  -d --detached          
```

For DevOps use cases, we can also recommend
```
# Chain command (downloads model)
cortex run <model> -d

# Specific model start
cortex model start
```

**Comment by namchuai** [comment]
@dan-homebrew, may I suggest for attach mode, we can remove the -a flag. Which means we only have two cases:
1. `cortex run tinyllama`, will start the chat in interactive mode.
2. `cortex run tinyllama -d`, will not start chat.

We shouldn't add both `-a` and `-d` because it's not making sense if user can supply both `=a` and `-d` at the same time.

**Comment by gabrielle-ong** [comment]
@namchuai does this PR deprecate `cortex chat`, or it'll be in a separate PR?
ie `cortex chat` is still working and in the prompt 
```
> cortex-nightly run tinyllama-d
tinyllama:1b-gguf model started successfully. Use `cortex-nightly chat tinyllama:1b-gguf` for interactive chat shell
```

**Comment by namchuai** [comment]
> @namchuai does this PR deprecate `cortex chat`, or it'll be in a separate PR? ie `cortex chat` is still working and in the prompt
> 
> ```
> > cortex-nightly run tinyllama-d
> tinyllama:1b-gguf model started successfully. Use `cortex-nightly chat tinyllama:1b-gguf` for interactive chat shell
> ```

oh, sorry @gabrielle-ong , this PR does not deprecate `cortex chat`. Is deprecate mean remove?

**Comment by gabrielle-ong** [comment]
Thanks @namchuai, yes to remove `cortex chat` - let's confirm with the team on discord

**Comment by gabrielle-ong** [comment]
Marking as complete, thanks @namchuai!
