### ISSUE TITLE
epic: Move Docs back into Cortex repo

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1428]
## Goal 

- Continue.dev and others are able to refer to `@docs`
- We are a small team and Docs should be part of Eng work

**Comment by hiento09** [comment]
Added @urmauur  here to update all the website links, i.e. when user visits jan.ai/cortex/homebrew, adn clicks the "edit this page"

**Comment by gabrielle-ong** [comment]
Thanks @hiento09 and @urmauur! Marking as complete
