### ISSUE TITLE
bug: Should not rename binary file - cortex v1.0.0-rc1 can not  start server

### ISSUE THREAD

**Issue by cloudherder** [janhq/cortex.cpp#1435]
### Cortex version

cortex-1.0.0-rc1-windows-amd64.tar.gz

### Describe the Bug

cortex v1.0.0-rc1 can not start server。

### Steps to Reproduce

1.cortex start -p 1234
2.display: Could not start server: 2

### Screenshots / Logs

[cortex-cli.log](https://github.com/user-attachments/files/17265008/cortex-cli.log)
![图片](https://github.com/user-attachments/assets/cc487600-4a52-4d75-aef8-637fee432e12)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by vansangpfiev** [comment]
Hi @cloudherder, seems like you renamed `cortex-beta` to `cortex`. Start server needs to call correct binary variant, for example `cortex-nightly`, `cortex-beta`, `cortex` (for stable release).
Please keep the binary as is.

**Comment by cloudherder** [comment]
> Hi @cloudherder, seems like you renamed `cortex-beta` to `cortex`. Start server needs to call correct binary variant, for example `cortex-nightly`, `cortex-beta`, `cortex` (for stable release). Please keep the binary as is.

Oh, really. According to your suggestion, the problem has been resolved. thank you!
