### ISSUE TITLE
bug: Failed to read connection when running model

### ISSUE THREAD

**Issue by JulienSorin** [janhq/cortex.cpp#1447]
### Cortex version

cortex-1.0.0-linux-amd64-local-installer.deb

### Describe the Bug

Impossible to run model in docker.

### Steps to Reproduce

1. docker run -it debian:trixie /bin/bash
2. apt update && apt install -y wget sudo
3. cd ~ && wget -O cortex.deb https://github.com/janhq/cortex.cpp/releases/download/v1.0.0/cortex-1.0.0-linux-amd64-local-installer.deb
4. apt install ./cortex.deb
5. cortex engines list
6. cortex pull llama3.1:8b-gguf
7. cortex run llama3.1:8b-gguf

### Screenshots / Logs

![{7FDDFC03-8578-48F7-954D-6A89E23CB00C}](https://github.com/user-attachments/assets/d440b81e-062d-4eb3-b428-fe3becbe46b1)

...

![{C49A2928-3828-40E9-9543-58CE28EAABC7}](https://github.com/user-attachments/assets/3bb7ee0b-9772-47c7-8409-3f4ed521bd76)

![{D08B2726-AFDD-441F-8F60-F8AC9515DE6C}](https://github.com/user-attachments/assets/21b2c738-6ec0-4cb6-a7cd-06b93cf7fe4e)

![{1142C160-1942-451E-A226-FA2C538FB395}](https://github.com/user-attachments/assets/b92fbda5-221c-4ac7-a344-77b8b2daa12f)

![{4360B2F5-53F3-49E7-90CE-AF4EB1A98FEF}](https://github.com/user-attachments/assets/a6f08fba-ee59-48b9-a3a8-62008a56b472)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by vansangpfiev** [comment]
Hi @JulienSorin, can you please share the cortex logs? They are in `/root/cortexcpp/logs` folder

**Comment by gabrielle-ong** [comment]
@JulienSorin following up - can you share your cortex logs, as well the Linux version you are using?

**Comment by gabrielle-ong** [comment]
Hi @JulienSorin, we've released cortex v1.0.1 and fixed lots of bugs 
We'll love if you can give it another go at running llama3.1. 

To update to cortex v1.0.1 (or download here: https://cortex.so/)
```
> cortex update
> cortex update --server
```

**Comment by gabrielle-ong** [comment]
@JulienSorin, closing this ticket for now - we've released a docker installation as of Cortex 1.0.3 - hope you can try it out. Feel free to create a new ticket if you've any issues
- [https://cortex.so/docs/installation/docker/](https://cortex.so/docs/installation/docker/)
- [https://github.com/janhq/cortex.cpp/tree/dev/docker](https://github.com/janhq/cortex.cpp/tree/dev/docker)
