### ISSUE TITLE
bug: [Not able to install on linux server]

### ISSUE THREAD

**Issue by chiragvels** [janhq/cortex.cpp#1449]
### Cortex version

Latest

### Describe the Bug

https://github.com/janhq/cortex.cpp?tab=readme-ov-file#linux-1

This steps not found after git clone.

### Steps to Reproduce

https://github.com/janhq/cortex.cpp?tab=readme-ov-file#linux-1

Steps not able to buidl.

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [x] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
Hi @chiragvels, what Linux version are you using? can you give us more details with your cortex.log and cortex-cli.log? in `/cortexcpp`?

**Comment by chiragvels** [comment]
I am able to install it now with cortex but model is not loaded. so I asked at discord channel and they suggested to try nightly versions. I am still not tried this yet.
I am using linux version Ubuntu 24.04.1 LTS.

Thanks,

**Comment by gabrielle-ong** [comment]
Hey @chiragvels! Yes great to have you on our discord!
We are improving the nightly version and releasing every night, will be great to know if it works for you.
Closing this Linux installation issue - we can continue the convo on discord if you need further help
