### ISSUE TITLE
bug: cors rest api

### ISSUE THREAD

**Issue by simboonlong** [janhq/cortex.cpp#1450]
### Cortex version

1.0.0

### Describe the Bug

local web application while trying to fetch REST API at `http://localhost:39281/v1/chat/completions`  resulted in CORS Access-Control-Allow-Origin error. Same issue at documentation page chat completion​ demo [here](https://cortex.so/api-reference/#tag/inference/post/v1/chat/completions):

<img width="1408" alt="cors" src="https://github.com/user-attachments/assets/0106b098-2d80-4da0-885a-88ff6d42acb9">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [x] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
@simboonlong 
Great catch, we will explore a fix for our API docs site calling a local API endpoint (running over http). 

In the mean time for you to test Cortex API, you can run cortex locally,
and test the APIs via our Swagger API page [http://127.0.0.1:39281](http://127.0.0.1:39281) or Postman
```
❯ cortex start
Server started
API Documentation available at: http://127.0.0.1:39281
Host: 127.0.0.1 Port: 39281
```

![Image](https://github.com/user-attachments/assets/f1825c9c-8182-4cdc-92b6-7207990728d3)

**Comment by simboonlong** [comment]
thank you for the follow up. yup postman is fine and interacting via cli works.

im thinking in terms of a flag, say `cortex start --no-cors` to allow all incoming requests with `addHeader("Access-Control-Allow-Origin", "*")`?

**Comment by gabrielle-ong** [comment]
Hi @simboonlong, thanks for the feature suggestion! 
On cortex-nightly, you are now able to turn CORS on and off
- CLI: cortex-nightly config --cors on|off`
- CLI: `cortex-nightly config --allowed_origins "localhost:39281,xxx"`
- API reference: https://cortex.so/api-reference#tag/configurations/get/v1/configs
- Test Requests work on our cortex.so API reference site (fixes your screenshot above)

Do give it a try on cortex-nightly! Will be out on cortex stable release next week
https://github.com/janhq/cortex.cpp?tab=readme-ov-file#local-installer-default

**Comment by simboonlong** [comment]
tried on v1.0.3, `--allowed_origins` works. thank you 🚀
