### ISSUE TITLE
bug: Cortex API needs to support `v1` path

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1455]
## Goal

- Some API endpoints do not have v1 (e.g. `/models`)
- Needs to have `v1`, otherwise we're going to get a lot of bug requests

**Comment by namchuai** [comment]
I think this PR from @vansangpfiev is handled it already https://github.com/janhq/cortex.cpp/pull/1443

However, I will recheck the swagger.

**Comment by gabrielle-ong** [comment]
@sangjanai transferring this to you, as a subtask of #1456. Feel free to close if completed

**Comment by gabrielle-ong** [comment]
Marking as complete, thanks @sangjanai
