### ISSUE TITLE
bug: Isolate stdout from the API server and CLI - I sent an API request, but it output an error message to an inactive shell session.

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1476]
### Cortex version

v1.0.0-168

### Describe the Bug

I have finished the shell session of models list, but somehow, when I send API requests, it keeps stdout from an inactive shell session. See attached screenshot, weird.

### Steps to Reproduce

1. Start API Server
2. Run any command such as models list
3. Send API request
4. See the shell output

### Screenshots / Logs

![Screenshot 2024-10-15 at 12 12 48](https://github.com/user-attachments/assets/ae4a8db1-f633-4859-bbe1-597bbc6a6f59)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [ ] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
@louis-jan checking if this is resolved for you with the latest v172? 
I dont get any stdout from the inactive shell session (which is good)

**Comment by louis-jan** [comment]
It still 😆 
<img width="571" alt="image" src="https://github.com/user-attachments/assets/c8a60eee-182e-44e0-8de8-e39906d9773c">

**Comment by gabrielle-ong** [comment]
Might be related to #1519, also getting Stdout in inactive terminal during `POST model/pull`
in v183

**Comment by vansangpfiev** [comment]
@gabrielle-ong Please help to verify, this should be fixed by v189

**Comment by gabrielle-ong** [comment]
@louis-jan verifying if this is fixed on your end, it's fixed on mine

**Comment by louis-jan** [comment]
Everything is good.  🚀
