### ISSUE TITLE
feat: cortex support custom prompt_template when load model

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1484]
This feature supports Jan or other applications that want to integrate Cortex as a server. When users want to change the prompt template, Cortex can directly load that prompt instead of saving it to model.yml and then loading the model from model.yml.

**Comment by gabrielle-ong** [comment]
QA: ✅ 
- API shouldn't save the prompt template to model.yaml file (this case is handled by POST `models/update`)
- try inputing a random prompt template, model should still load successfully (optional parameter)
- usecase is requested by Louis when he intergrating Jan
- to NOT save the prompt template when loading model if user accidentally modifies prompt template during `models/start`
 ![Image](https://github.com/user-attachments/assets/4bce0818-afcd-417c-8fc0-6a75cf8c798d)
