### ISSUE TITLE
bug: `v1.0.0-169` returns "Error: ≤B÷" but starts model

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1486]
### Cortex version

v1.0.0-169

### Describe the Bug

1. Run `cortex run tinyllama`
2. Get a  "Error: ≤B÷" in the logs
3. Model still starts
4. There is no error in the logs (only in cortex-cli)

There clearly is an error somewhere, that doesn't seem to affect model running. 

### Screenshots / Logs

[cortex.log](https://github.com/user-attachments/files/17377673/cortex.log)
[cortex-cli.log](https://github.com/user-attachments/files/17377674/cortex-cli.log)

![image](https://github.com/user-attachments/assets/9dc8e4b3-fa9c-4d21-ab8c-8af916f8fedb)

This behavior also persists when I do not start the cortex server beforehand: 

![image](https://github.com/user-attachments/assets/1f88a910-6c6e-451e-8391-32f00ab1ff76)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by vansangpfiev** [comment]
@gabrielle-ong Can you please help to check again? This should be solved by the latest nightly.

**Comment by gabrielle-ong** [comment]
Thanks Sang, marking as complete,- fixed on Windows v178
![image](https://github.com/user-attachments/assets/65701d80-ed89-40e1-ab5d-68bf359a48b8)
