### ISSUE TITLE
bug: 10s for Time-to-first-Token on 3090

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1488]
### Cortex version

v1.0.0-169

### Describe the Bug

- `cortex run tinyllama:gguf` takes 10s for Time-to-first Token
- See Loom video for illustration
- This is even with me doing `cortex run tinyllama:gguf` before starting the chat session

We should either:
- Fix this
- Or, if it indeed takes 10s, have a clearer UX that shows that we are generating first token (otherwise, it looks like it's a bug)

### Screenshots / Logs

https://www.loom.com/share/87b8540c016a4c4ab19d33e82a2349c7

[cortex.log](https://github.com/user-attachments/files/17378110/cortex.log)
[cortex-cli.log](https://github.com/user-attachments/files/17378111/cortex-cli.log)

Hardware: 
- 3090

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
@vansangpfiev @dan-homebrew 
I got a longer inference time (5-10s) on the very first request after a fresh install of cortex-nightly (Windows)
Subsequent chat completions were immediate

Attaching logs and timestamp (will edit this comment)
09:04:44 - this took a longer time (started generating, then I truncated the response)
09:05:11 - this was fast 

Does the first inference need to instantiate something? If yes then I think it's reasonable

[cortex.log](https://github.com/user-attachments/files/17458479/cortex.log)
[cortex-cli.log](https://github.com/user-attachments/files/17458480/cortex-cli.log)

**Comment by vansangpfiev** [comment]
> @vansangpfiev @dan-homebrew I got a longer inference time (5-10s) on the very first request after a fresh install of cortex-nightly (Windows) Subsequent chat completions were immediate
> 
> Attaching logs and timestamp (will edit this comment) 09:04:44 - this took a longer time (started generating, then I truncated the response) 09:05:11 - this was fast
> 
> Does the first inference need to instantiate something? If yes then I think it's reasonable
> 
> [cortex.log](https://github.com/user-attachments/files/17458479/cortex.log) [cortex-cli.log](https://github.com/user-attachments/files/17458480/cortex-cli.log)

For the first run, the model response is slower because it is not warmed up and cached yet. However, we have already called the warm-up function when load the model, so this long response time should happen on `loading model`.
Seems like we do not warm up the model properly and still need to fix this.
As @gabrielle-ong mentioned, the issue only happens on the first time we load/chat with model.

**Comment by dan-menlo** [comment]
@vansangpfiev Yes, we need to shift the waiting time to `loading model`. This should not happen on user input, but when the model is loaded/started. 

I have noticed this problem in Jan as well - "Generating Response" takes a very long time. 

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/994a0f51-520c-4b1d-a080-15b3a848846b">

**Comment by vansangpfiev** [comment]
@gabrielle-ong Can you pull the latest engine (v0.1.35) and try again?

**Comment by gabrielle-ong** [comment]
Fresh install of v191 on windows, super fast first inference. Thanks @vansangpfiev!

**Comment by dan-menlo** [comment]
@vansangpfiev Tested on v1.0.0-192, "felt" faster (from a UX perspective). Great job on the quick turnaround!
