### ISSUE TITLE
planning: Cortex CLI should be a layer on top of the API Server

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1492]
Sub-ticket from Epic: https://github.com/janhq/cortex.cpp/issues/1415
### Problem Statement

Cortex CLI does not use the API Server in all commands

### Feature Idea

Cortex CLI should be a layer on top of the API Server. 
This is quite straight forward except for `cortex pull` and `cortex engines install`.
We use `libcurl` UI/UX for download progress for above CLI commands and get the models, engines directly from Github, HF, ... The execution via `/v1/models/pull` and `/v1/engines/install` requires a lot of changes in UI/UX and logic (will need `websockets` to track download progress).
Related ticket: https://github.com/janhq/cortex.cpp/issues/1423

For `cortex pull` and `cortex engines install` using API server, can we move them into v1.0.2 instead of v1.0.1?

cc: @dan-homebrew @0xSage @gabrielle-ong @namchuai @nguyenhoangthuan99

**Comment by vansangpfiev** [comment]
Another thing: because CLI is a layer on top of the API server, CLI will start the Server if it is not started, before executing any command.

**Comment by gabrielle-ong** [comment]
Marking as complete, as a subtask under #1415
