### ISSUE TITLE
bug: v170 regression: Download progress bar doesnt appear

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1494]
### Cortex version

v170

### Describe the Bug

1. `cortex pull` model
2. Download progress stats doesnt appear, 

### Steps to Reproduce

<img width="710" alt="image" src="https://github.com/user-attachments/assets/83c4512a-1d7e-428e-bcb6-100d4f52f695">
During download:
<img width="689" alt="image" src="https://github.com/user-attachments/assets/de06cb1f-b41f-4afa-baf9-7d24547dd93b">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by namchuai** [comment]
Please retest with latest version. It's my mistake and I got it covered in PR #1460

**Comment by gabrielle-ong** [comment]
Confirmed resolved, thanks @namchuai!
