### ISSUE TITLE
bug: Could not able to run models since 172

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1505]
### Cortex version

172-176

### Describe the Bug

Model run is broken at 172; I was unable to start HF model models.
It worked fine before.

```
https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q8_0.gguf
```

### Steps to Reproduce

1. Update to version 172 or the latest version 176.
2. Clean.
3. Pull a HF model
4. Run
5. See errors.

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/ec061839-d217-49f7-9018-23aa05e82f5b)
![image](https://github.com/user-attachments/assets/7df26d6c-ad4f-4cf4-9d3d-e409e72527fd)

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by nguyenhoangthuan99** [comment]
This issue has been resolved by this pr #1507

**Comment by gabrielle-ong** [comment]
@nguyenhoangthuan99 / @vansangpfiev for v183,
- I'm getting the same error as Louis' first picture
- For huggingface models only (cortexso models are ok)
- `cortex run <Model ID>` is successful but `cortex run <model alias>` throws the uncaught exception YAML::BadSubscript

![Image](https://github.com/user-attachments/assets/74bf617b-ff50-4184-a961-ef47167e0cd2)[cortex-cli.log](https://github.com/user-attachments/files/17430491/cortex-cli.log)
[cortex.log](https://github.com/user-attachments/files/17430490/cortex.log)

**Comment by vansangpfiev** [comment]
Hi @gabrielle-ong, we will deprecate `model_alias` soon https://github.com/janhq/cortex.cpp/issues/1410#issuecomment-2418721440. So can we mark this bug as `won't fix`?

**Comment by gabrielle-ong** [comment]
True agree, thanks @vansangpfiev
This will be handled as part of #1512 next week
- deprecating model_alias
- using regex for cortex run, so this error should not occur
