### ISSUE TITLE
bug: `cortex models list` incorrectly starts server (regression 172-176)

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1509]
### Cortex version

v176

### Describe the Bug

Worked correctly for v172, regression for v176

1. server is not running
2. `cortex models list`
starts server - is this expected?
then successfully lists models

### Screenshots / Logs

<img width="1222" alt="image" src="https://github.com/user-attachments/assets/a045982a-58c7-47a0-951a-d2f9af53e8b9">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by vansangpfiev** [comment]
@gabrielle-ong It is expected. I mentioned it here https://github.com/janhq/cortex.cpp/issues/1492#issuecomment-2415707894
