### ISSUE TITLE
bug: `cortex models delete` fails with 400

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1515]
### Cortex version

v178

### Describe the Bug

`Models delete` fails
on VM: test-ubuntu-app-cpu-1

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/18163df1-5895-4fa1-8a3c-4ac8dc39f727)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by vansangpfiev** [comment]
Hi @gabrielle-ong, the disk of `test-ubuntu-app-cpu-1` was full. After freed some space, I could not reproduce the issue.
Can you please check?

**Comment by gabrielle-ong** [comment]
Closing, thanks Sang!
