### ISSUE TITLE
bug: models download service - stout `Validating download items`

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1519]
### Cortex version

v183

### Describe the Bug

While QAing #1242 via postman, sends stdout to CLI in inactive terminal
`Validating download items, please wait..`
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/e2636466-42b0-433d-b756-384bb795e9c4">
<img width="752" alt="image" src="https://github.com/user-attachments/assets/06354ea1-7a17-4b24-a59e-5f61a1a4fd0c">

### Steps to Reproduce

1. POST models/pull starts download
2. POST models/pull halfway shows downloaded bytes
3. DELETE models/pull stops the download

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by namchuai** [comment]
@vansangpfiev is already fixed this one in https://github.com/janhq/cortex.cpp/pull/1526

**Comment by gabrielle-ong** [comment]
Marking as complete, thanks @vansangpfiev and @namchuai
