### ISSUE TITLE
planning: `openapi/jan.json` to `cortex.json`

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1534]
Followup task from #1456 

**Problem**
- `openapi/jan.json` is currently used as the single source of truth for API
- QN: should it be separated to `cortex.json`?
- What are the implications on Devops for cortex.so?

**Success Criteria**
- 

**Tasklist**
- [ ]

**Comment by namchuai** [comment]
I think it's simple naming, need to coordinate with https://cortex.so because its using `openapi/jan.json` as well.

**Comment by dan-menlo** [comment]
@namchuai We have moved https://cortex.so into the Cortex repo, to make it easier to handle changes like this. 

- Let's go ahead to change it to `openai/cortex.json`
- As part of this, please make sure to update Cortex Docs site as well (verify locally)

**Comment by gabrielle-ong** [comment]
✅ Verified cortex docs site locally, marking as complete, thanks @namchuai
