### ISSUE TITLE
idea: Support more parameters for /v1/models/start

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1537]
### Problem Statement

Currently, /v1/models/start only accept prompt_template parameter

### Feature Idea

Should accept more parameters like `context_length`
Scenario: 
- When the user sends `start` request, cortex will override parameters loaded from model.yml by request's parameters.
- The content of model.yml will be kept as-is.

**Comment by vansangpfiev** [comment]
Need to add below parameters:
```
cache_enabled: bool
ngl: int
n_parallel: int
cache_type: string
ctx_len: int

```

**Comment by vansangpfiev** [comment]
To support vision model, we also need to add `mmproj` parameter, type: string
```
mmproj: string
llama_model_path: string
model_path: string
```

**Comment by gabrielle-ong** [comment]
API: accept parameters (though it accepts any parameter - is there some guardrail)
![Image](https://github.com/user-attachments/assets/17439a94-02ca-4d29-89f4-52f2052e84cc)

Eg test n_parallel
![Image](https://github.com/user-attachments/assets/1a09f7ce-ad69-4192-b899-2c3304c2a78f)
