### ISSUE TITLE
bug: remove embeddings from the -h menu in cortex

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1541]
### Cortex version

v1.0.1

### Describe the Bug

We don't support `embeddings` yet, so should remove it from `cortex -h`

### Steps to Reproduce

`cortex -h`

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
Thanks @vansangpfiev! Marking complete in v198
