### ISSUE TITLE
planning: Cortex has a Redhat compatible version

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1564]
## Goal 

- Cortex should support RedHat distribution methods

**Comment by hiento09** [comment]
Added @vansangpfiev here. We need to change the updater strategy for Linux if we support multiple types of package distribution.

**Comment by dan-menlo** [comment]
KIV to Sprint 25, to focus on Jan -> Cortex refactor

**Comment by hiento09** [comment]
We will ship linux installer as a bash script instead of support multiple linux distro. #1670
