### ISSUE TITLE
feat: Swagger should support all API Endpoints

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1583]
## Goal 

- Document existing API Endpoints (e.g. `cortex start`)
- Investigate whether we can autogenerate Drogon Swagger

## Tasklist

- [ ] Documenting existing API endpoints that are missing in Swagger
- [ ] Dan to intro to Marty (Drogon maintainer)

**Comment by nguyenhoangthuan99** [comment]
- [x] I added all openAI API field in the Chat Completion documentation in this pr #1589 
- [x] All API endpoint for `/v1` is in the API, the `models/import` is supported in this pr #1600 
- [x] We need to add API doc for `/health`, `/destroy` to stop server.
- [x] For all parts that has not been implemented yet in chat completion documentation, we should link PR for it.
