### ISSUE TITLE
Implement hardware detection function

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1591]
Hardware service needs to provide below information:
```
{
  "cpu": {
    "arch": "string",
    "cores": "string",
    "model": "string",
    "instructions": ["string"]
  },
  "os": {
    "version": "string",
    "name": "string"
  },
  "ram": {
    "total": "string",
    "available": "string",
    "type": "string"
  },
  "storage": {
    "total": number,
    "available": number,
    "type": "string"
  },
  "gpus": [
    {
      "model": "string",
      "vram": "string",
      "driver_version": "string"
    }
  ],
  "power": {
    "battery_life": number,
    "charging_status": "string",
    "is_power_saving": boolean
  },
  "monitors": [
    {
      "resolution": "string",
      "refresh_rate": number,
      "resolution":"string
    }
  ]
}
```

**Comment by vansangpfiev** [comment]
Obtaining GPU information for AMD graphics cards can be complex:
- On Windows: The[ AGS SDK](https://github.com/GPUOpen-LibrariesAndSDKs/AGS_SDK/tree/master) provides valuable GPU information but does not include GPU usage metrics. To address this limitation, we can explore alternative methods using the [Display Library](https://github.com/GPUOpen-LibrariesAndSDKs/display-library), which offers examples that may help resolve the issue.
- On Linux: The [ROCm ](https://github.com/ROCm/ROCm) platform appears to be the most suitable option for accessing GPU information and usage data.

**Comment by gabrielle-ong** [comment]
Marking as complete with #1568
