### ISSUE TITLE
feat: Download URL for Cortex .tar binaries

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1606]
### Problem Statement
Feature request by Linux users to support multiple installations (apart from .deb)
- Tar
- AppImage (Fedora)
- Yum (RedHat)

### Discussions:
- Script based Linux installation?

### Task List
- [x] download url for tar binary (latest version of Cortex nightly, beta, stable)
- [ ]  

## User inputs
<img width="830" alt="image" src="https://github.com/user-attachments/assets/6fd1f607-f812-497d-b1b5-0e5beda07098">
<img width="867" alt="image" src="https://github.com/user-attachments/assets/3a5a0693-8f4e-40df-87e3-682768087ef9">
https://x.com/homebrewltd/status/1851549472297517351: "only works on Debian based distro"

**Comment by dan-menlo** [comment]
@gabrielle-ong I think the correct way to term this problem, is more of supporting multiple Linux install methods: 

- AppImage (Fedora)
- Yum (RedHat)

It might also be wise for us to shift Linux install to a script-based approach, i.e. an `install.sh`

This should be assigned to @hiento09 as part of a larger epic on Linux install.

**Comment by gabrielle-ong** [comment]
Thanks @Hien for the Binary download links
Windows: https://app.cortexcpp.com/download/latest/windows-amd64-binary
Linux: https://app.cortexcpp.com/download/latest/linux-amd64-binary
Macos: https://app.cortexcpp.com/download/latest/mac-universal-binary

Beta
Windows: https://app.cortexcpp.com/download/beta/windows-amd64-binary
Linux: https://app.cortexcpp.com/download/beta/linux-amd64-binary
Macos: https://app.cortexcpp.com/download/beta/mac-universal-binary

Nightly
Windows: https://app.cortexcpp.com/download/nightly/windows-amd64-binary
Linux: https://app.cortexcpp.com/download/nightly/linux-amd64-binary
Macos: https://app.cortexcpp.com/download/nightly/mac-universal-binary

**Comment by gabrielle-ong** [comment]
Thank you @hiento09!
![Image](https://github.com/user-attachments/assets/f0b95840-844d-4c7b-98cc-146398eb5f8c)
