### ISSUE TITLE
chore: Cortex Docs should be updated with Docs and API Endpoints

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1613]
## Goal 

- Cortex Docs and README should be up-to-date with latest changes
- Goal: by end-Monday, Cortex Docs are good enough to
- Goal: epics start with Docs first, and then once approved coding can start

I would like the full team to understand how the OpenAPI format works, to enable us to handle documentation scalably. 

# Docs Site

## Overall

- [x] Document how to create Redirects for Docusaurus @hiento09 
- [ ] Are we able to split up OpenAPI file into smaller parts? (e.g. by route)

## Get Started

**Installation**

Owner: @hiento09 

- [x] Installation Page (i.e,. how does our installer work)
    - [x] Differences between cortex stable, beta, nightly. Remove repetition from elsewhere
    - [x] Local vs network installer
    - [x] Docker @hiento09 (thank you!)

**Quickstart**
**Basic Usage**

Owner: @gabrielle-ong 

- [x] Combine Basic Usage and API Server

**Architecture**
- [x] Cortex Data Folder @hiento09 
- [x] cortex.db @vansangpfiev 
- [x] .cortexrc @vansangpfiev 
    - [x] e.g. What fields are in `.cortexrc`
- [x] Updater @vansangpfiev 
    - [x] e.g. how Updater works

## Capabilities

We should talk about capabilities, and link to the appropriate API References. 

- [x] Pulling Models @namchuai (thank you!)
     - [ ] Model Formats (i.e. our Cortex Model repo format), or Huggingface GGUF repo
- [x] Running Models @nguyenhoangthuan99 
     - [x] Should explain runtime params vs. model.yaml
     - [x] Should explain Models use Engines
- [x] Engine Management @namchuai 
     - [ ] Should give high-level overview of Engine Management, e.g. different types, Versions, Variants
     - [ ] llama.cpp (should give instructions on how to install, update, change versions/variants, explain AVX2, AVX-512 etc)
     - [ ] Building Engine Extensions (should give instructions on EngineI.h)
- [ ] Hardware Awareness @vansangpfiev 
- [ ] Text Generation
- [ ] Embeddings

## Guides

- [x] Function Calling @nguyenhoangthuan99 
- [x] Structured Outputs @nguyenhoangthuan99 

# API Reference

## Chat

Assignee: @nguyenhoangthuan99 

### API Reference
- [x] /chat/completions 

## Pulling Models

Assignee: @namchuai 

### API Reference
- [x] Pull a Model
- [x] Stop Model Download
- [x] Import Model

## Running Models

Assignee: @vansangpfiev 

### API Reference
- [x] List Models
- [x] Start Models
- [x] Stop Model
- [x] Get Model
- [x] Delete model 
- [x] Update model

## Engines

Assignee: @namchuai 

### API Reference
- [x] List available engines
- [x] Get an engine
- [x] Install an engine
- [x] Uninstall an engine

## Server

Assignee: @vansangpfiev 

### Docs
- Basic Usage

### API Reference
- [ ] Start, Stop
- [ ] Update
- [x] Terminate
- [x] Check health

## Hardware

Assignee: @vansangpfiev (write Docs before implementing, keep in PR)

### Docs
- Hardware Awareness section

### API Reference
- Hardware APIs

**Comment by gabrielle-ong** [comment]
Leftover chores from #1575 - @gabrielle-ong 
- [x] CLI commands - remove nightly, beta commands
- [x] Advanced Installation
    - [x] Network vs Local Installer (in Advanced Installation)
    - [ ] linux binary links
- [ ] Github readme - add Linux binary

**Comment by hiento09** [comment]
# Redirect Instruction:
- Create a file `docs/_redirects`.
- Add a redirect using the following syntax: `source_path destination_path code`, for example, `/team /about/team 302`. This means https://cortex.so/team will redirect to https://cortex.so/about/team.
- File `docs/_redirects` example
  ```
  /home301 / 301
  /home302 / 302
  /querystrings /?query=string 301
  /twitch https://twitch.tv
  /trailing /trailing/ 301
  /notrailing/ /nottrailing 301
  /page/ /page2/#fragment 301
  /blog/* https://blog.my.domain/:splat
  /products/:code/:name /products?code=:code&name=:name
  ```

# Refer to:
- https://github.com/janhq/jan/blob/dev/docs/_redirects
- https://developers.cloudflare.com/pages/configuration/redirects/

cc @janhq/cortex @dan-homebrew @gabrielle-ong

**Comment by vansangpfiev** [comment]
For Server API endpoints, we only have 
- Terminate  (Stop)
- Check health
We don't have `Start` and `Update` endpoints. CLI is taking the responsibility for updating.
