### ISSUE TITLE
bug: macos network installer not install llama-cpp engines by default

### ISSUE THREAD

**Issue by hiento09** [janhq/cortex.cpp#1616]
## Context
- From nightly version v1.0.0-191, cortex-install on macos not install llama-cpp engine by default

## Goal
- Fix the bug
- Add e2e testing for installer

**Comment by hiento09** [comment]
Thanks @vansangpfiev for finding out this bug

**Comment by gabrielle-ong** [comment]
Hi @hiento09, I tried on `v223` mac network installer  
- seems that llama-cpp engine is not installed, am I missing something?

Steps:
uninstalled engines, uninstalled cortex-nightly, reinstalled cortex-nightly
![Image](https://github.com/user-attachments/assets/9c146c7e-9669-488b-ad69-dd96aa69f137)

**Comment by gabrielle-ong** [comment]
Thanks @hiento09! Sorry I'm still not getting it on install on the v227 network installer
- to confirm, llama-cpp should be listed in `engines list` upon install right?
- it does successfully pull llama-cpp on `cortex run`
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/266ace96-0b18-4ba7-a49d-f730d36d6444">

**Comment by hiento09** [comment]
Hi @gabrielle-ong , can you help test version 226? Version 226 was built from my branch for testing and has not been merged into the dev branch. Version 227 is the nightly version from yesterday and does not include my fix PR.

**Comment by gabrielle-ong** [comment]
Adding the logs for future reference - thanks @hiento09 for investigating. tested v226 -
1. Works on VM `(test-macos-13-1)`
2. Doesnt work on my local mac - `/var/log/install.log` attached
[cortex-installer.log](https://github.com/user-attachments/files/17655978/cortex-installer.log)

**Comment by gabrielle-ong** [comment]
tested on v228 for branch `feat/cicd-docker`, works on my local now. Thanks @hiento09!
<img width="580" alt="image" src="https://github.com/user-attachments/assets/511adcb1-d301-4238-94f7-e2e3c96cffa3">
