### ISSUE TITLE
epic: API and CLI to enable/disable CORS

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1635]
**Problem**
- Users are facing a CORS configuration issue when using a different frontend (eg ChatGPT)
- Also encountered on test requests sent from the docs /api-reference site 
- We should offer the option to enable/disable CORS (similar to Jan API server)
```
Access to XMLHttpRequest at 'http://127.0.0.1:39281/v1/chat/completions' from origin 'https://cortex.so' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource
```

**Success Criteria**
- Ensure it works on browsers (Safari may have stricter CORs)

**Tasklist**
- [ ] 

Reference bug reports
- #1450
- discord cortex-help: 
<img width="580" alt="image" src="https://github.com/user-attachments/assets/34790a0a-2e55-436f-a494-6b4ac708498c">

![image](https://github.com/user-attachments/assets/f232fceb-4fd3-48af-80b0-19907daf4d92)

**Comment by dan-menlo** [comment]
@namchuai For this, let's quickly spec out an API and CLI for activating/deactivating CORS. 

- This API will be used to power Jan's API Server CORS toggle

![Image](https://github.com/user-attachments/assets/5be8ae12-c624-4c30-aae4-32deafd623c3)

**Comment by namchuai** [comment]
@dan-homebrew @gabrielle-ong 
For enabling / disabling CORS, I propose:
> **My assumption. Correct me if I'm wrong or you have different idea**
> 1. ~~Enable/Disable CORS will only be applied after server restart.~~ Server restart not required
> 2. Default CORS will be `On` (Enabled) for user to easily playing around and run it from https://cortex.so or their local host.
> 3. Flag stored at `.cortexrc`

## API interface
### CLI

#### Help command
```
Subcommands for managing configurations
Usage:
cortex config status for listing all API server configuration.
cortex config --cors [on/off] to toggle CORS.
cortex config --allowed_origins [comma separated origin] to set a list of allowed origin

Options:
  -h,--help                   Print this help message and exit
  --cors TEXT [*]             [on/off] Toggling CORS.
  --allowed_origins TEXT [*]  Allowed origins for CORS. Comma separated. E.g. http://localhost,https://cortex.so

Configurations:
  status                      Print all configurations
```
#### List Server Configurations
```sh
cortex config status
```

#### Update CORS configuration
```sh
cortex config --cors on|off
```
Response
1. Successfully update
```sh
CORS updated to ON|OFF
```
2. Failed update
```sh
CORS update failed. Reason: ...
```

### HTTP API
#### Update CORS configuration
```
PATCH http://127.0.0.1:39281/config
```
Body
```json
{
    "cors": true | false
}
```
Response:
```json
{
    "message": "Configuration updated successfully"
}
```
#### Get configurations
```
GET http://127.0.0.1:39281/config
```
Response
```json
{
    "cors": true | false
}
```

**Comment by gabrielle-ong** [comment]
Thanks @namchuai! 
1. Seems like we dont need to restart server, much better UX. Ill edit the spec above for clarity
2. Can we add our 2 `allowed_origins` by default? `http://localhost:39281`, `http://127.0.0.1:39281`
3. Bug - Some requests fail on our swagger site: 
with `cors = true`, `allowed_origins = http://127.0.0.1:39281`, 
`GET /configs` works, but `POST /models/start` doesnt work (discord convo)

![image](https://github.com/user-attachments/assets/74dcca3c-4178-4ba7-a494-6b5fea609ac5)
![image](https://github.com/user-attachments/assets/df633e7b-2a2e-4d2c-95e0-3ba0dd98583f)

**Comment by gabrielle-ong** [comment]
And thank you for adding docs! #1652

**Comment by gabrielle-ong** [comment]
Hi @namchuai, thanks for fixing bug for POST action and default origins.

3 more questions/bugs:
1. I turned CORS off but I am still able to send a request to `http://127.0.0.1:39281/` (may be linked to below)
=> I expect to get a CORS error in console when I turn off CORS

2. API: PATCH `cortex config --allowed_origins` is not updated.
I expect allowed_origins to change from 3 to 0
![Image](https://github.com/user-attachments/assets/a9f8d6ba-ea01-4bbc-a9a2-18e65959fddf)
I expect the allowed_origins to change from 3 to 2. CORs successfully updated to false.
![Image](https://github.com/user-attachments/assets/745b947d-458d-4c83-bff6-3103fecdd68b)

3. Via CLI:
✅ Successfully adds / updates allowed_origins. 
![Image](https://github.com/user-attachments/assets/7f0d9beb-7846-478d-8882-447f2dacb5fe)
❓ But I cant remove the list of allowed origins (do I put empty list?)
![Image](https://github.com/user-attachments/assets/82760b4d-c057-4a8c-b030-e5c44fc1b0a6)

**Comment by namchuai** [comment]
@gabrielle-ong , the parameter requires a list, not a map, I can see you putting `allowed_origins: {}` which is not correct. 
<img width="874" alt="Screenshot 2024-11-12 at 14 31 21" src="https://github.com/user-attachments/assets/2737a5df-b208-4908-b2af-f2b68515c0a9">

```
I turned CORS off but I am still able to send a request to http://127.0.0.1:39281/ (may be linked to below)
=> I expect to get a CORS error in console when I turn off CORS

```
About this, may I have your configuration screenshot?

```
❓ But I cant remove the list of allowed origins (do I put empty list?)
```
You don't need double quotes. In order to make the list empty, just run `cortex-nightly config --allowed_origins`

**Comment by gabrielle-ong** [comment]
I see, gotcha on `cortex-nightly config --allowed_origin` and allowed_origins [] list
1. Here's the Configuration for CORS = off
![image](https://github.com/user-attachments/assets/7d86447c-1eb5-400a-82b4-d25b67432349)
![image](https://github.com/user-attachments/assets/66c76ede-a7c1-4584-850e-33e7c4b3baae)
But I can still send a chat completion
![image](https://github.com/user-attachments/assets/46075ec7-4edd-4394-9760-03dab007cba2)

2. I see. Then checking - The test request swagger is incorrect? it shows {0: ..., 1: ...}
![image](https://github.com/user-attachments/assets/e29c6c94-5688-4400-ab35-3d456b9e116d)
![image](https://github.com/user-attachments/assets/ce7443e5-d26e-4768-8e3e-e828a59a9e5b)

**Comment by namchuai** [comment]
@gabrielle-ong 
```
Here's the Configuration for CORS = off
But I can still send a chat completion
```
This is weird. I test on my end and I see that I have CORS error. Maybe we can jump on a quick call to solve it out.

```
I see. Then checking - The test request swagger is incorrect? it shows {0: ..., 1: ...}
```
You are right. Let me quickly update the example

**Comment by gabrielle-ong** [comment]
@namchuai  thanks for checking and updating the example. 
Sorry for the trouble. So no fix required -
I restarted the server and it seems to correctly get the CORS error
Setting CORs yes = successfully sends the request
![Image](https://github.com/user-attachments/assets/90142788-fcb9-493e-abe8-9ec098117a9e)

**Comment by namchuai** [comment]
Hmm, regarding the update docs, I was wrong. https://cortex.so/api-reference#tag/configurations/patch/v1/configs displayed correct. I'm suspecting this issue comes from scalar.

**Comment by gabrielle-ong** [comment]
Thanks James for CORS! Closing it and separating the Scalar issue (local displays differently from deployed)
