### ISSUE TITLE
bug:  Max context length automatically defaults to 4096 tokens

### ISSUE THREAD

**Issue by ux-han** [janhq/cortex.cpp#1668]
### Jan version

0.5.8

### Describe the Bug

https://discord.com/channels/1107178041848909847/1204617960615055401/1301375861282312235

For imported models only, Jan did try to fall back to hub model.json, so it uses the maximum number instead:

<img width="688" alt="Screenshot 2024-11-03 at 8 04 28 PM" src="https://github.com/user-attachments/assets/ea057d00-237d-41fd-bcb1-064a3230dd74">

We need to find a better solution for this. 

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by louis-jan** [comment]
Current: 
The current default value = min(8192, max_model_context_length)

Where it should be:
Differentiate between model metadata and run settings:
1. Users can define model load parameters (both CLI and API, currently API is supported), default is the formula above.
2. Model.yaml should maintain GGUF metadata.

Session settings: 
-> Stored in threads/assistants accordingly - client’s perspective
-> Run arguments - CLI perspective

**Comment by TC117** [comment]
```
PS C:\WINDOWS\system32> cortex-nightly.exe models start tinyllama:gguf --ctx_len 1024
Start downloading..
model.gguf          100%[====================] 00m:00s 637.81 MB/637.81 MB
model.yml           100%[====================] 00m:00s 545.00 B/545.00 B
Model tinyllama:gguf downloaded successfully!
tinyllama:gguf model started successfully. Use `cortex-nightly.exe run tinyllama:gguf` for interactive chat shell
PS C:\WINDOWS\system32> cortex-nightly.exe ps
+-------------------+-----------+--------+-----------+---------------------------------+
| Model             | Engine    | RAM    | VRAM      | Up time                         |
+-------------------+-----------+--------+-----------+---------------------------------+
| tinyllama:1b-gguf | llama-cpp | 0.00 B | 636.18 MB | 2 hours, 14 minutes, 14 seconds |
+-------------------+-----------+--------+-----------+---------------------------------+
| tinyllama:gguf    | llama-cpp | 0.00 B | 636.18 MB | 4 minutes, 5 seconds            |
+-------------------+-----------+--------+-----------+---------------------------------+
PS C:\WINDOWS\system32> cortex-nightly.exe run tinyllama:gguf --ctx_len 1024
In order to exit, type `exit()`
>
```
