### ISSUE TITLE
idea: Linux Installation Script (Bash)

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1670]
### Problem Statement

- We need to support all distros
- Bash script likely the most straightforward

### Feature Idea

Considerations:
- Bundles individual libraries / can use old versions of dependencies
- security considerations of libraries for flatpak maintainer?

**Comment by hiento09** [comment]
For bash installer script it will be a network installer, not local install

**Comment by hiento09** [comment]
## Current Updater Flow for Linux
- User types cortex -v.
- Check the remote version against the current version => display a message to run sudo cortex update.
- User types sudo cortex update.
- Download the .deb file locally.
- Run a command to extract and install the .deb file.

## Suggested Flow with Bash Script
- User types cortex -v.
- Check the remote version against the current version → display a message to run sudo cortex update.
- User types sudo cortex update.
- Run the installation script with is-update=true passed as a parameter.  (Ex: `curl -s https://raw.githubusercontent.com/janhq/cortex/feat/linux-bash-install-script/engine/templates/linux/install.sh | sudo bash -s -- --channel stable --is_update`)

## The installation bash script will perform the following tasks (all logic for update will be put into the bash script):
- Detect whether the user is performing a new installation or an update.
- Detect whether a .deb package needs to be installed or if the binary file should be installed directly.


How do you think @dan-homebrew @0xSage  @gabrielle-ong @vansangpfiev

**Comment by TC117** [comment]
``` 
Prerequisites
- OpenMPI
- curl
- jq
- tar
```
- [x] Missing Prerequisites
```
tinb@tinb:~$ curl -s https://raw.githubusercontent.com/janhq/cortex/main/engine/templates/linux/install.sh | sudo bash -s
[sudo] password for tinb:
jq could not be found ...
Please install jq then rerun this script
tinb@tinb:~$
```

- [x] Install successful
```
tinb@tinb:~$ curl -s https://raw.githubusercontent.com/janhq/cortex/main/engine/templates/linux/install.sh | sudo bash -s 
Downloading cortex stable version 1.0.3 from https://github.com/janhq/cortex.cpp/releases/download/v1.0.3/cortex-1.0.3-linux-amd64-network-installer.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24.9M  100 24.9M    0     0  10.4M      0  0:00:02  0:00:02 --:--:-- 30.7M
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'cortexcpp' instead of '/tmp/cortex.deb'
The following NEW packages will be installed:
  cortexcpp
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
Need to get 0 B/26.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /tmp/cortex.deb cortexcpp amd64 1.0.3 [26.2 MB]
Selecting previously unselected package cortexcpp.
(Reading database ... 197731 files and directories currently installed.)
Preparing to unpack /tmp/cortex.deb ...
Unpacking cortexcpp (1.0.3) ...
Setting up cortexcpp (1.0.3) ...
Download cortex.llamacpp engines by default for user tinb
Config file not found. Creating one at /home/tinb/.cortexrc
Default data folder path: /home/tinb/cortexcpp
Starting server ...
Could not start server
HTTP error: Could not establish connection
Uninstall script created at /usr/bin/cortex-uninstall.sh
Installation complete. Run cortex-uninstall.sh to uninstall.
tinb@tinb:~$ cortex -v
v1.0.3
tinb@tinb:~$
```
- [x] Uninstall successful
```
tinb@tinb:~$ sudo /usr/bin/cortex-uninstall.sh 
[sudo] password for tinb: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  cortexcpp
0 upgraded, 0 newly installed, 1 to remove and 22 not upgraded.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 197733 files and directories currently installed.)
Removing cortexcpp (1.0.2) ...
Do you want to delete the ~/cortexcpp data folder and file ~/.cortexrc? (yes/no) [default: no]
yes
Deleting cortex data folders...
Removing /home/tinb/cortexcpp
Removing /home/tinb/.cortexrc
tinb@tinb:~$ cortex ps 
cortex: command not found
tinb@tinb:~$
```

**Comment by gabrielle-ong** [comment]
@hiento09 Thanks! Adding a discord User @david_12870 report:
"#Cortex-help: Install script fails on alma linux 9.4":

Error: 
```
Failed to get JSON from https://api.github.com/repos/janhq/cortex.llamacpp/releases/latest: CURL request failed: Problem with the SSL CA cert (path? access rights?) - curl_utils.h:216
20241122 10:51:28.470110 UTC 558641 ERROR Failed to get latest llama.cpp version: CURL request failed: Problem with the SSL CA cert (path? access rights?
```

Fix: 
- on alma linux 9 (probably RHEL as well), you need to sudo ln -s /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/ssl/certs/ca-certificates.crt

**Comment by hiento09** [comment]
Thanks @gabrielle-ong for pointing this out! 

Linux systems will need to, one way or another, add the CA certificates of trusted sites. Otherwise, any `curl` or `wget` command run on that OS will result in the similar error. Most Linux users will be aware of this. 

Let me update the troubleshooting section (https://github.com/janhq/cortex.cpp/issues/1761) to include guidance for users on what they should do when encountering this issue since the method for adding CA certificates varies between distributions.

**Comment by gabrielle-ong** [comment]
Closing as complete, thank you @hiento09!
