### ISSUE TITLE
planning: prioritize GPUs with CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1679]
**Problem**
We don't define a logic to prioritize GPUs yet. 
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
**Success Criteria**
- Need to support prioritize GPUs

**Tasklist**

## Linked Bugs
- requires priority for multi-GPU #1458

**Comment by TC117** [comment]
- [x] added priorities into db
![image](https://github.com/user-attachments/assets/12804091-f08e-46f4-9beb-4bc1a0f6eb4f)

need help to check with multiple GPU machine @hiento09
