### ISSUE TITLE
epic: Cortex track delete models on file system

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1683]
### Cortex version

1.0.2

### Describe the issue and expected behaviour

- Problem: Jan users are used to deleting the model folder, rather than deleting on Jan UI
- Users cannot just remove the /models folder as the backend has to update cortex.db
- We should track the file system and update cortex.db so that no action is required for them

Approaches (@louis-jan & @namchuai to add on)
- Build cortex.db as a quick lookup table, but like caching, we still monitor folder changes for better performance.
- Scan it once on launch in the background
- To propose filescan interval
- Alternative: `model has been deleted! -> delete in cortex.db`

## QA:
- Delete model folder (or specifically model.yml file)
- expected result: cortex models list does not list the model

**Comment by gabrielle-ong** [comment]
Thanks @namchuai! Closing this issue, released with cortex 1.0.3 and Jan 0.5.9

QA: 
Delete model folder (or specifically model.yml file)
expected result: cortex models list does not list the model

**Comment by louis-jan** [comment]
Hi @gabrielle-ong this one is not included in cortex 1.0.3 and Jan 0.5.9. I think we scoped out this. cmiiw @namchuai

**Comment by gabrielle-ong** [comment]
Thanks @louis-jan for pointing out -  the QA is incorrect and this feature is not in Cortex 1.0.3. 
The above behaviour is due to another fix: #1420

**Comment by gabrielle-ong** [comment]
QAed on Cortex 1.0.3-252 - Thanks @namchuai for discussing and fixing these issues

1. Windows: stinput when model file was removed
![image](https://github.com/user-attachments/assets/83e8bd56-b887-4c3e-a5c4-c5461609468f)

2. Mac: Successfully removes from `models list` but not cortex.db
- Removing entire folder of models removes multiple models from `models list` eg /huggingface.co
- Removing model folder removes model from `models list` eg /Bartowski
- But cortex.db still has model
<img width="400" alt="image" src="https://github.com/user-attachments/assets/46659435-022c-4609-a35a-3e0f1fddf093">
<img width="344" alt="image" src="https://github.com/user-attachments/assets/1f9aa507-07c0-48cd-8676-0944f39018d9">

**Comment by gabrielle-ong** [comment]
✅ thanks @namchuai !
QA: on file system folder delete -> models deleted on 1/ `models list` and 2/ sqlite db 

Windows
![image](https://github.com/user-attachments/assets/f16e3e07-d2a8-4fd1-a1de-872c94e5a013)

Mac
<img width="348" alt="image" src="https://github.com/user-attachments/assets/0cad1f21-93b2-4560-928a-8f9813958d3e">
