### ISSUE TITLE
feat: Engines API endpoints should be consistent

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1684]
### Problem Statement

Standardize Engines APIs to have query params in the body

### Feature Idea

1. Installation / Uninstall: `engines/install`
2. Get / Set Default: `engines/default`
3. Load / Unload: `engines/load`
4. Update `engines/update`

**Comment by gabrielle-ong** [comment]
@namchuai Qn: 
5. Get Engine: does it remain `GET /engine/NAME` (like `GET Models/ID`)? 
- and how does this work with versions, variants?
- Currently we allow `GET /engines/{engine_type}/{version}`

**Comment by namchuai** [comment]
@gabrielle-ong ,
```
5. Get Engine: does it remain GET /engine/NAME (like GET Models/ID)?
```
Yes, API below will list all installed llamacpp engines. Currently we don't have `GET /{version}` because actually there's not much data for a version.
```
curl --location 'http://127.0.0.1:3928/v1/engines/llama-cpp'
```
```
[
    {
        "engine": "llama-cpp",
        "name": "mac-arm64",
        "version": "v0.1.39"
    }
]
```

**Comment by gabrielle-ong** [comment]
Thanks @namchuai! Marking as complete and pending #1675 from me
