### ISSUE TITLE
feat: API to add HuggingFace token

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1697]
### Problem Statement

Currently, we need to open `.cortexrc` file to add HF token.

### Feature Idea

Support API to allow user to add, update, delete HF token.

**Comment by gabrielle-ong** [comment]
Thanks @vansangpfiev, closing. successfully update HF API (fake token)
 <img width="637" alt="image" src="https://github.com/user-attachments/assets/038046b2-6bfc-446e-93a1-648e2c1ae417">
