### ISSUE TITLE
bug: `engines install` CLI progress bar

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1711]
### Cortex version

1.0.2-244

### Describe the issue and expected behaviour

Engines download bar is duplicated
Previously similar error for models download (solved #1655)

### Steps to Reproduce

1. `cortex engines install llama-cpp`

### Screenshots / Logs

![Screenshot 2024-11-20 150418](https://github.com/user-attachments/assets/4441d7d6-2b44-4fd3-a903-6e6458fcef60)
![Screenshot 2024-11-20 150435](https://github.com/user-attachments/assets/7dadb872-c829-4239-bdc8-4f6b12587309)
![Screenshot 2024-11-20 150840](https://github.com/user-attachments/assets/c971412a-9545-457b-9db4-9d18d39d2dbb)

### What is your OS?

- [X] Windows
- [ ] Mac Silicon
- [ ] Mac Intel
- [ ] Linux / Ubuntu

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by vansangpfiev** [comment]
This bug happens when the progress bar can't be fit in 1 terminal line. Let me try to improve it.

**Comment by gabrielle-ong** [comment]
Closing, thanks @vansangpfiev!
<img width="868" alt="image" src="https://github.com/user-attachments/assets/eb8e5a71-2b76-4e87-ba18-392ee87e42dc">
