### ISSUE TITLE
bug: could not start any model when change system locale to German

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1722]
### Cortex version

v1.0.3

### Describe the issue and expected behaviour

Change the system locale to German, start model.
Expected: Start model successfully

### What is your OS?

- [X] Windows
- [ ] Mac Silicon
- [ ] Mac Intel
- [ ] Linux / Ubuntu

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by gabrielle-ong** [comment]
Closing as resolved in Jan
