### ISSUE TITLE
bug: model float parameters return from cortex is not rounded

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1734]
### Cortex version

1.0.3

### Describe the issue and expected behaviour

When making requests to /models, it returns unrounded model parameter float values that differ from the values defined in the model.yml file.

The fix for #1387 wasn’t covered in the cases.

![CleanShot 2024-11-28 at 09 33 43](https://github.com/user-attachments/assets/49b6de3c-25e8-4148-9cf6-cf2fe4a18383)

![CleanShot 2024-11-28 at 09 34 19](https://github.com/user-attachments/assets/48a30713-e9e9-4ed8-9ce0-157f931f50ae)

### Expected results
1. It should return rounded values that are defined in the model.yaml file.

### Check after the fix
1. Float numbers should have decimal places (maximum 2) and not round to an integer.
2. Integer numbers should not be converted to floats with decimal places.

### Steps to Reproduce

1. Pull a model
2. Get /models

### Screenshots / Logs

![CleanShot 2024-11-28 at 09 33 43](https://github.com/user-attachments/assets/49b6de3c-25e8-4148-9cf6-cf2fe4a18383)

![CleanShot 2024-11-28 at 09 34 19](https://github.com/user-attachments/assets/48a30713-e9e9-4ed8-9ce0-157f931f50ae)

### What is your OS?

- [ ] Windows
- [X] Mac Silicon
- [ ] Mac Intel
- [ ] Linux / Ubuntu

### What engine are you running?

- [X] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)

**Comment by ux-han** [comment]
This issue persists:

<img width="329" alt="Screenshot 2024-12-01 at 2 12 05 PM" src="https://github.com/user-attachments/assets/1cab1585-ee5c-4468-a513-2690d507832a">

**Comment by louis-jan** [comment]
The latest version fixes this issue, where `/models` now also returns rounded values.
