### ISSUE TITLE
feat: logger

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#22]
Currently, we are planning to use [trantor](https://github.com/an-tao/trantor) for logging in cortex.cpp. We need to provide following feature.
- [ ] log to terminal
- [ ] log to file
- [ ] roll new file when log file size is too large

**Comment by nguyenhoangthuan99** [comment]
Trantor currently provide a function to add custom output file 
![image](https://github.com/user-attachments/assets/52137b86-94df-46dd-a681-6abf2b7f89bf)

We need to implement custom function to write output stream to file.

**Comment by nguyenhoangthuan99** [comment]
The logic for logging file:
- log files is placed under ~/cortex/logs/ folder
- maximum size of logfile is 20 MB (configurable), if file size larger than that, will split to new file
- at each run the log file will follow this template `{base_name}.{year month date}-{random number base on process id}.{shard number}.log`. For example `cortex.240821-151342.000000.log`
