### ISSUE TITLE
engine: AMD GPU support

### ISSUE THREAD

**Issue by hiento09** [janhq/cortex.cpp#323]
## Tasklist

- [ ] Can this be solved via llama.cpp? (e.g. compiled for Vulkan and ROCm)
- [x] https://github.com/janhq/cortex.llamacpp/issues/9
- [ ] [https://github.com/janhq/jan/issues/913](https://github.com/janhq/jan/issues/913)

## Original Post

**Problem**
We need a new nitro bin file that support AMD GPU for both windows and linux

**Success Criteria**
- new nitro bin file support AMD GPU
- Integrate to Jan app

**Comment by tikikun** [comment]
Tutorial to compile nitro on that system above (details in link https://gist.github.com/cgmb/6ae0d118bf357fc4576a7568b85e1c45 ):

First step, install AMD things (for details link: https://gist.github.com/cgmb/6ae0d118bf357fc4576a7568b85e1c45) :
<img width="1115" alt="image" src="https://github.com/janhq/nitro/assets/22268502/9d0da5fd-8da2-4749-83e4-d6fc77c9d05c">

After that just build nitro with below flag:
```bash
CC=/opt/rocm/llvm/bin/clang CXX=/opt/rocm/llvm/bin/clang++ \
    cmake -H. -Bbuild -DLLAMA_HIPBLAS=ON -DAMDGPU_TARGETS= gfx1011 -DCMAKE_BUILD_TYPE=Release 
```
and

```bash
make
```

**Comment by hiento09** [comment]
I was able to build nitro with above flag successfully using this docker image https://hub.docker.com/r/rocm/dev-ubuntu-22.04

**Comment by hiento09** [comment]
![image](https://github.com/janhq/nitro/assets/136591877/17b03c2b-bcdc-48da-830d-4403375de023)
AWS reject our quota request, we may need to consider purchasing for some AMD GPU, @tikikun , @dan-jan

**Comment by hiepxanh** [comment]
@hiento09 can you provide bin file? I cannot make the build run on my WSL 2 windows

**Comment by tikikun** [comment]
rename to ROCm support since vulkan already supported

**Comment by tikikun** [comment]
still have ROCm build left @hiento09 @hiro-v

**Comment by louis-jan** [comment]
Experimental feature: 0.4.7

**Comment by Van-QA** [comment]
converting this to epic to close https://github.com/janhq/jan/issues/913

**Comment by 0xSage** [comment]
@Van-QA can we queue this up after trtllm for Cam? 🙏

**Comment by Van-QA** [comment]
hi @0xSage, if you look at the sprint / status, you can see that it's already in the n‌ext spr‌int

**Comment by louis-jan** [comment]
> @louis-jan No it's not This is AMD RoCm (equivalent to NVIDIA CUDA), not Vulkan. I'm moving this one back to Icebox as of now

So why linked PR

**Comment by louis-jan** [comment]
Reassign

**Comment by louis-jan** [comment]
From Jan: I think a UX enhancement is needed. (GPU settings)

**Comment by ux-han** [comment]
- Closed as dup of https://github.com/janhq/jan/issues/3529
