### ISSUE TITLE
cortex models list

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#41]

**Comment by nguyenhoangthuan99** [comment]
walk through all `<model_id>.yaml` in models/ folder and print `model_id` with `engine`.

**Comment by nguyenhoangthuan99** [comment]
To use this command:
`./cortex-cpp models list`

It will show results like this


![Image](https://github.com/user-attachments/assets/27c14df8-4e28-4fd7-8485-3ef042418f72)
