### ISSUE TITLE
epic: Support OpenAI-equivalence

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex.cpp#629]
## Specs
- https://www.notion.so/jan-ai/OpenAI-Equivalent-API-2ce2b524ea02448c87cd9d9fb424f0a2?pvs=4

## Tasklist
- [x] janhq/jan#2655
- [x] https://github.com/janhq/cortex/issues/561

**Comment by dan-menlo** [comment]
Closing this issue as a non-goal (for now) for cortex.cpp
