### ISSUE TITLE
engine: Intel OpenVino

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex.cpp#677]
## Goal

- Intel is launching their Lunar Lake chips, which have an iGPU (67 TOPs), NPU (48 TOPs)
- Intel recommends OpenVINO, which takes full advantage of their Lunar Lake chips

## Key Decisions

- Are there other ways to solve for this? #470

**Comment by dan-menlo** [comment]
Closing in favor of #470

**Comment by RyanMetcalfeInt8** [comment]
Just to point out that this is very much related to this issue: https://github.com/janhq/jan/issues/3764

The engine that I am working / testing on uses OpenVINO GenAI framework as an inference engine (i.e. swaps out llama.cpp for OpenVINO GenAI).
