### ISSUE TITLE
epic: Cortex supports Audio (STT)

### ISSUE THREAD

**Issue by imtuyethan** [janhq/cortex.cpp#743]
## Goal 

- Cortex supports audio engine

## Tasklist

- [ ] Change name to `whispercpp-engine`? for semantic naming https://github.com/janhq/cortex.cpp/discussions/1167

# Original Post
https://www.notion.so/jan-ai/Cortex-supports-Audio-STT-632714576a0b4143b58001349b576ca9?pvs=4

**Comment by ux-han** [comment]
Already done but haven't merged

**Comment by gabrielle-ong** [comment]
Closing as duplicate of https://github.com/janhq/jan/issues/3488
