### ISSUE TITLE
bug: dangling process after uninstall cortex

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex.cpp#917]
1. uninstall cortex 
2. Issue:
1337 port was unused
but 3929 was running

I wasn't running a server before this either, so not sure why cortexcpp was using port

@louis-jan mentioned sm about adding a process watchdog

**Comment by louis-jan** [comment]
Fixed in npm script. cc @hiento09 for brew, apt and winget

**Comment by hiento09** [comment]
Thanks @louis-jan for remining
@dungpham91 can you help to handle for winget? I will PIC for brew and apt.

**Comment by ux-han** [comment]
What are the updates for this @hiento09

**Comment by hiento09** [comment]
We can close this since this is from cortex platform
