### ISSUE TITLE
bug: Slow load on Windows on first time run of Cortex

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#929]
**Describe the bug**
Cortex on Windows always takes more than 10s on the first run, then it's less than 1s.

**To Reproduce**
1. Install cortex from NPM
2. Try run any commands
3. See the error

**Expected behavior**
It should load consistently between each attempt.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dan-menlo** [comment]
@louis-jan Is this issue still valid (i.e. Cortex Platform still has this issue), or can we deprecate?

**Comment by dan-menlo** [comment]
@vansangpfiev I am reassigning this to the Cortex team - if this issue does not exist for the C++ implementation, you can proceed to close this ticket

**Comment by dan-menlo** [comment]
Closing this as related to Cortex Platform

**Comment by dan-menlo** [comment]
Tracking this as a test case in https://github.com/janhq/cortex.cpp/issues/1147
