### ISSUE TITLE
bug: libengine.dylib not found

### ISSUE THREAD

**Issue by simboonlong** [janhq/cortex.cpp#953]
**Describe the bug**
When `cortex run llama3`, libengine.dylib not found in folder.

**To Reproduce**
1. `brew install cortexso`
2. `cortex pull llama3`
3. `cortex run llama3`

**Expected behavior**
Model should run.

**Screenshots**
Log:

<img width="1411" alt="logs" src="https://github.com/user-attachments/assets/8392315d-25b4-4db4-b9b6-819a5a937063">

Directory:
<img width="715" alt="directory" src="https://github.com/user-attachments/assets/6cb64b46-1434-4cab-9909-051bcf6f81bf">

Strange empty `Users` folder gets created too. `Users` > `<username>` > `cortex` > `telemetry`.

**Desktop (please complete the following information):**
 - macOS: 14.2.1

**Comment by louis-jan** [comment]
Hey @simboonlong could you please help upgrade to the latest version? I think those have been addressed.

Engine & Users 

After installed the latest version, please try `cortex engines llamacpp init`

**Comment by simboonlong** [comment]
This is tested to indeed work with 0.5.0-1 version. it assumes that i do a npm global install of `npm i -g cortexso`. 

However if i do the brew install of `brew install cortexso`, i seem to always stuck at cortexso 0.1.1 version installed in `Cellar`.

**Comment by simboonlong** [comment]
https://github.com/janhq/homebrew-cortexso/blob/bfcd5a09e37de50ea1bdce235b51cc059038eb79/Formula/cortexso.rb#L6

**Comment by louis-jan** [comment]
@simboonlong yeah, we are resolving brew to bump to a newer update.

**Comment by louis-jan** [comment]
This should be addressed when we refactoring cortex-cpp.

**Comment by dan-menlo** [comment]
@simboonlong FYI, we are currently re-writing Cortex to be a full C++ codebase, instead of JS + C++ as before. We will launch v0.1 in coming weeks, so expect some changes. 

I'll be closing this ticket, but reference it in our MVP test coverage so we ensure this does not happen in v0.1.
